tinyMCE.addI18n('de.typolinks_dlg',{
page:"Contao-Seiten",
file:"Contao-Dateien",
link_title:"Link einf\u00FCgen/bearbeiten",
link_url:"Adresse",
link_target:"Fenster",
link_target_same:"Im selben Fenster \u00F6ffnen",
link_target_blank:"Neues Fenster \u00F6ffnen",
link_titlefield:"Titel",
link_is_email:"Bei der Adresse scheint es sich um eine E-Mail-Adresse zu handeln. Wollen Sie das dazu ben\u00F6tigte mailto: voranstellen?",
link_is_external:"Bei der Adresse scheint es sich um einen externen Link zu handeln. M\u00F6chten Sie, dass zur korrekten Verlinkung ein http:// vorangestellt wird?",
link_list:"Linkliste",
image_title:"Vorschaubild einf\u00FCgen/bearbeiten",
image_list:"Bilderliste",
image_src:"Bild-Url",
image_dimensions:"Breite/H\u00F6he",
image_alt:"Beschreibung",
image_class:"CSS-Klasse",
image_resize_mode:"Modus",
image_crop:"Exaktes Format",
image_proportional:"Proportional",
image_box:"An Rahmen anpassen",
image_rel:"Lightbox",
image_rel_single:"Einzelnes Element",
image_rel_multi:"Galerie"
});