tinyMCE.addI18n('sv.typolinks_dlg',{
page:'Contao-sidor',
file:'Contao-filer',
link_title:"L\u00E4gg till/editera l\u00E4nk",
link_url:"L\u00E4nk-URL",
link_target:"M\u00E5l",
link_target_same:"\u00D6ppna l\u00E4nk i samma f\u00F6nster",
link_target_blank:"\u00D6ppna l\u00E4nk i nytt f\u00F6nster",
link_titlefield:"Titel",
link_is_email:"URL:en du angav verkar vara en E-postadress. Vill du l\u00E4gga till det n\u00F6dv\u00E4ndiga mailto:-prefixet?",
link_is_external:"URL:en du angav verkar vara en extern l\u00E4nk. Vill du l\u00E4gga till det n\u00F6dv\u00E4ndiga http://-prefixet?",
link_list:"L\u00E4nklista",
image_title:"L\u00E4gg till/editera lightbox-bild",
image_list:"Bildlista",
image_src:"Bild-URL",
image_dimensions:"Bredd/H\u00F6jd",
image_alt:"Beskrivning",
image_class:"CSS-klass",
image_rel:"Typ",
image_rel_single:"Enkel bild",
image_rel_multi:"Bildgalleri",
image_rel_empty:"Enbart tumnagel",
image_resize_mode:"Omskalningsmetod",
image_crop:"Exakta m\u00E5tt",
image_proportional:"Proportionellt",
image_box:"Passa in i box"
});