editAreaLoader.lang["sv"]={
new_document: "skapa nytt dokument",
search_button: "sök och ersätt",
search_command: "sök nästa / öppna sökdialog",
search: "sök",
replace: "ersätt",
replace_command: "ersätt / öppna sökdialog",
find_next: "hitta nästa",
replace_all: "ersätt alla",
reg_exp: "regular expressions",
match_case: "exakt sökning",
not_found: "kunde ej hittas.",
occurrence_replaced: "förekomster ersatta.",
search_field_empty: "Sökord saknas",
restart_search_at_begin: "Slutet av texten uppnått. Börja från början..",
move_popup: "flytta sökdialogen",
font_size: "--Fontstorlek--",
go_to_line: "gå till rad",
go_to_line_prompt: "gå till rad nummer:",
undo: "ångra",
redo: "återställ",
change_smooth_selection: "slå på/av vissa visningsfunktioner (smartare men mer CPU-krävande)",
highlight: "växla syntax-markering på/av",
reset_highlight: "återställ syntax-markering (om den blivit osynkad med texten)",
word_wrap: "växla automatisk radbrytning på/av",
help: "om",
save: "spara",
load: "öppna",
line_abbr: "Rad",
char_abbr: "Kol",
position: "Position",
total: "Total",
close_popup: "stäng dialog",
shortcuts: "Genvägar",
add_tab: "sätt in tabulatur i texten",
remove_tab: "ta bort tabulatur i text",
about_notice: "OBS: Syntax-markering fungerar enbart med liten textstorlek.",
toggle: "Växla editor",
accesskey: "Kortkommando",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Beräknar...",
fullscreen: "fullskärm",
syntax_selection: "--Syntax--",
close_tab: "Stäng fil"
};
