/* CodeMirror, copyright (C) 2011 by Marijn Haverbeke, MIT-style License. */
var CodeMirror=(function(){function l(R,aZ){var a9={},aU=l.defaults;for(var bo in aU){if(aU.hasOwnProperty(bo)){a9[bo]=(aZ&&aZ.hasOwnProperty(bo)?aZ:aU)[bo]}}var bD=a9.document;var bm=bD.createElement("div");bm.className="CodeMirror";bm.innerHTML='<div style="overflow: hidden; position: relative; width: 1px; height: 0px;"><textarea style="position: absolute; width: 2px;" wrap="off"></textarea></div><div class="CodeMirror-scroll cm-s-'+a9.theme+'"><div style="position: relative"><div style="position: absolute; height: 0; width: 0; overflow: hidden;"></div><div style="position: relative"><div class="CodeMirror-gutter"><div class="CodeMirror-gutter-text"></div></div><div class="CodeMirror-lines"><div style="position: relative"><pre class="CodeMirror-cursor">&#160;</pre><div></div></div></div></div></div></div>';
if(R.appendChild){R.appendChild(bm)}else{R(bm)}var bT=bm.firstChild,bQ=bT.firstChild,aB=bm.lastChild,aC=aB.firstChild,au=aC.firstChild,bi=au.nextSibling,aM=bi.firstChild,bO=aM.firstChild,aF=aM.nextSibling.firstChild,aa=aF.firstChild,ae=aa.nextSibling;if(a9.tabindex!=null){bQ.tabindex=a9.tabindex}if(!a9.gutter&&!a9.lineNumbers){aM.style.display="none"}var aE=new m(),an=new m(),ad;var bb,bK=[new c("")],a3,a0=new f(),i;
bk();var aO={from:{line:0,ch:0},to:{line:0,ch:0},inverted:false};var a2,bu,ac;var bg,bI,aH,aj,bG;var bd=0,bs=0,bz=0,aL=null;var S,by;var aG="";bL(function(){ag(a9.value||"");bg=false})();setTimeout(az,20);j(aB,"mousedown",bL(ao));if(!t){j(aB,"contextmenu",bL(al))}j(aC,"dblclick",bL(bc));j(aB,"scroll",function(){ab([]);if(a9.onScroll){a9.onScroll(bH)}});j(window,"resize",function(){ab(true)});j(bQ,"keyup",bL(bh));
j(bQ,"keydown",bL(ar));j(bQ,"keypress",bL(a6));j(bQ,"focus",aA);j(bQ,"blur",ay);j(aB,"dragenter",function(bV){bV.stop()});j(aB,"dragover",function(bV){bV.stop()});j(aB,"drop",bL(ai));j(aB,"paste",function(){am();bF()});j(bQ,"paste",function(){bF()});j(bQ,"cut",function(){bF()});var X;try{X=(bD.activeElement==bQ)}catch(aS){}if(X){aA()}else{ay()}function L(bV){return bV>=0&&bV<bK.length}var bH={getValue:ba,setValue:bL(ag),getSelection:bB,replaceSelection:bL(ah),focus:function(){am();
aA();az();bF()},setOption:function(bV,bW){a9[bV]=bW;if(bV=="lineNumbers"||bV=="gutter"){N()}else{if(bV=="mode"||bV=="indentUnit"){bk()}else{if(bV=="readOnly"&&bW=="nocursor"){bQ.blur()}else{if(bV=="theme"){aB.className=aB.className.replace(/cm-s-\w+/,"cm-s-"+bW)}}}}},getOption:function(bV){return a9[bV]},undo:bL(bw),redo:bL(bU),indentLine:bL(function(bV){if(L(bV)){aq(bV,"smart")}}),historySize:function(){return{undo:a0.done.length,redo:a0.undone.length}
},matchBrackets:bL(function(){ap(true)}),getTokenAt:function(bV){bV=af(bV);return bK[bV.line].getTokenAt(bb,aD(bV.line),bV.ch)},cursorCoords:function(bV){if(bV==null){bV=aO.inverted}return bq(bV?aO.from:aO.to)},charCoords:function(bV){return bq(af(bV))},coordsChar:function(bW){var bX=K(aF);var bV=aW(Math.min(bK.length-1,bd+Math.floor((bW.y-bX.top)/bJ())));return af({line:bV,ch:a8(aW(bV),bW.x-bX.left)})
},getSearchCursor:function(bW,bX,bV){return new av(bW,bX,bV)},markText:bL(function(bW,bV,bX){return bL(Q(bW,bV,bX))}),setMarker:ak,clearMarker:Z,setLineClass:bL(aK),lineInfo:W,addWidget:function(bX,bW,bV){var bX=br(af(bX),true);bW.style.top=(bd*bJ()+bX.yBot+a4())+"px";bW.style.left=(bX.x+bj())+"px";aC.appendChild(bW);if(bV){bS(bX.x,bX.yBot,bX.x+bW.offsetWidth,bX.yBot+bW.offsetHeight)}},lineCount:function(){return bK.length
},getCursor:function(bV){if(bV==null){bV=aO.inverted}return B(bV?aO.from:aO.to)},somethingSelected:function(){return !F(aO.from,aO.to)},setCursor:bL(function(bV,bW){if(bW==null&&typeof bV.line=="number"){aR(bV.line,bV.ch)}else{aR(bV,bW)}}),setSelection:bL(function(bW,bV){bt(af(bW),af(bV||bW))}),getLine:function(bV){if(L(bV)){return bK[bV].text}},setLine:bL(function(bV,bW){if(L(bV)){bl(bW,{line:bV,ch:0},{line:bV,ch:bK[bV].text.length})
}}),removeLine:bL(function(bV){if(L(bV)){bl("",{line:bV,ch:0},af({line:bV+1,ch:0}))}}),replaceRange:bL(bl),getRange:function(bW,bV){return a5(af(bW),af(bV))},operation:function(bV){return bL(bV)()},refresh:function(){ab(true)},getInputField:function(){return bQ},getWrapperElement:function(){return bm}};function ag(bV){a0=null;var bW={line:0,ch:0};bf(bW,{line:bK.length-1,ch:bK[bK.length-1].text.length},n(bV),bW,bW);
a0=new f()}function ba(bX){var bY=[];for(var bW=0,bV=bK.length;bW<bV;++bW){bY.push(bK[bW].text)}return bY.join("\n")}function ao(b2){var bV=ac;ac=null;for(var bY=b2.target();bY!=bm;bY=bY.parentNode){if(bY.parentNode==bO){if(a9.onGutterClick){a9.onGutterClick(bH,k(bO.childNodes,bY)+bd)}return b2.stop()}}if(t&&b2.button()==3){al(b2)}if(b2.button()!=1){return}var bW=Y(b2),b4=bW,bX;if(!bW){if(b2.target()==aB){b2.stop()
}return}if(!i){aA()}b2.stop();if(bV&&+new Date-bV<400){return aJ(bW.line)}aR(bW.line,bW.ch,true);function b0(){am();bg=true;bZ();b1()}function b3(b5){var b7=Y(b5,true);if(b7&&!F(b7,b4)){if(!i){aA()}b4=b7;aN(bW,b7);bg=false;var b6=bM();if(b7.line>=b6.to||b7.line<b6.from){bX=setTimeout(bL(function(){b3(b5)}),150)}}}var bZ=j(bD,"mousemove",bL(function(b5){clearTimeout(bX);b5.stop();b3(b5)}),true);var b1=j(bD,"mouseup",bL(function(b5){clearTimeout(bX);
var b6=Y(b5);if(b6){aN(bW,b6)}b5.stop();b0()}),true)}function bc(bV){var bW=Y(bV);if(!bW){return}be(bW);bV.stop();ac=+new Date}function ai(bZ){var b2=Y(bZ,true),bW=bZ.e.dataTransfer.files;if(!b2||a9.readOnly){return}if(bW&&bW.length&&window.FileReader&&window.File){var b1=bW.length,b0=Array(b1),bX=0;for(var bV=0;bV<b1;++bV){bY(bW[bV],bV)}function bY(b5,b4){var b3=new FileReader;b3.onload=function(){b0[b4]=b3.result;
if(++bX==b1){bl(b0.join(""),af(b2),af(b2))}};b3.readAsText(b5)}}else{try{var b0=bZ.e.dataTransfer.getData("Text");if(b0){bl(b0,b2,b2)}}catch(bZ){}}}function ar(bZ){if(!i){aA()}var bY=bZ.e.keyCode;if(q&&bY==27){bZ.e.returnValue=false}var bX=(r?bZ.e.metaKey:bZ.e.ctrlKey)&&!bZ.e.altKey,bW=bZ.e.ctrlKey||bZ.e.altKey||bZ.e.metaKey;if(bY==16||bZ.e.shiftKey){a2=a2||(aO.inverted?aO.to:aO.from)}else{a2=null}if(a9.onKeyEvent&&a9.onKeyEvent(bH,s(bZ.e))){return
}if(bY==33||bY==34){bC(bY==34);return bZ.stop()}if(bX&&((bY==36||bY==35)||r&&(bY==38||bY==40))){bN(bY==36||bY==38);return bZ.stop()}if(bX&&bY==65){bn();return bZ.stop()}if(!a9.readOnly){if(!bW&&bY==13){return}if(!bW&&bY==9&&aw(bZ.e.shiftKey)){return bZ.stop()}if(bX&&bY==90){bw();return bZ.stop()}if(bX&&((bZ.e.shiftKey&&bY==90)||bY==89)){bU();return bZ.stop()}}aL=(bX?"c":"")+bY;if(aO.inverted&&G.hasOwnProperty(aL)){var bV=H(bQ);
if(bV){bu={anchor:bV.start};b(bQ,bV.start,bV.start)}}bF(aL)}function bh(bV){if(a9.onKeyEvent&&a9.onKeyEvent(bH,s(bV.e))){return}if(bu){bu=null;bg=true}if(bV.e.keyCode==16){a2=null}}function a6(bX){if(a9.onKeyEvent&&a9.onKeyEvent(bH,s(bX.e))){return}if(a9.electricChars&&bb.electricChars){var bV=String.fromCharCode(bX.e.charCode==null?bX.e.keyCode:bX.e.charCode);if(bb.electricChars.indexOf(bV)>-1){setTimeout(bL(function(){aq(aO.to.line,"smart")
}),50)}}var bW=bX.e.keyCode;if(bW==13){if(!a9.readOnly){ax()}bX.stop()}else{if(!bX.e.ctrlKey&&!bX.e.altKey&&!bX.e.metaKey&&bW==9&&a9.tabMode!="default"){bX.stop()}else{bF(aL)}}}function aA(){if(a9.readOnly=="nocursor"){return}if(!i&&a9.onFocus){a9.onFocus(bH)}i=true;bv();if(bm.className.search(/\bCodeMirror-focused\b/)==-1){bm.className+=" CodeMirror-focused"}M()}function ay(){if(i&&a9.onBlur){a9.onBlur(bH)
}clearInterval(ad);a2=null;i=false;bm.className=bm.className.replace(" CodeMirror-focused","")}function bf(b2,b1,bZ,bW,bV){if(a0){var bX=[];for(var bY=b2.line,b0=b1.line+1;bY<b0;++bY){bX.push(bK[bY].text)}a0.addChange(b2.line,bZ.length,bX);while(a0.done.length>a9.undoDepth){a0.done.shift()}}O(b2,b1,bZ,bW,bV);if(bZ.length<5){a7(b2.line,b2.line+bZ.length)}}function aQ(b1,b0){var bZ=b1.pop();if(bZ){var bX=[],bV=bZ.start+bZ.added;
for(var bW=bZ.start;bW<bV;++bW){bX.push(bK[bW].text)}b0.push({start:bZ.start,added:bZ.old.length,old:bX});var bY=af({line:bZ.start+bZ.old.length-1,ch:z(bX[bX.length-1],bZ.old[bZ.old.length-1])});O({line:bZ.start,ch:0},{line:bV-1,ch:bK[bV-1].text.length},bZ.old,bY,bY)}}function bw(){aQ(a0.done,a0.undone)}function bU(){aQ(a0.undone,a0.done)}function O(b6,bZ,cb,bV,cc){var ca=false,bY=aG.length;for(var b7=b6.line;
b7<=bZ.line;++b7){if(bK[b7].text.length==bY){ca=true;break}}var b2=bZ.line-b6.line,b1=bK[b6.line],bW=bK[bZ.line];if(b1==bW){if(cb.length==1){b1.replace(b6.ch,bZ.ch,cb[0])}else{bW=b1.split(bZ.ch,cb[cb.length-1]);var b3=[b6.line+1,b2];b1.replace(b6.ch,b1.text.length,cb[0]);for(var b7=1,b9=cb.length-1;b7<b9;++b7){b3.push(new c(cb[b7]))}b3.push(bW);bK.splice.apply(bK,b3)}}else{if(cb.length==1){b1.replace(b6.ch,b1.text.length,cb[0]+bW.text.slice(bZ.ch));
bK.splice(b6.line+1,b2)}else{var b3=[b6.line+1,b2-1];b1.replace(b6.ch,b1.text.length,cb[0]);bW.replace(0,bZ.ch,cb[cb.length-1]);for(var b7=1,b9=cb.length-1;b7<b9;++b7){b3.push(new c(cb[b7]))}bK.splice.apply(bK,b3)}}for(var b7=b6.line,b9=b7+cb.length;b7<b9;++b7){var b5=bK[b7].text;if(b5.length>bY){aG=b5;bY=b5.length;ca=false}}if(ca){bY=0;aG="";for(var b7=0,b9=bK.length;b7<b9;++b7){var b5=bK[b7].text;
if(b5.length>bY){bY=b5.length;aG=b5}}}var bX=[],b0=cb.length-b2-1;for(var b7=0,b5=a3.length;b7<b5;++b7){var b8=a3[b7];if(b8<b6.line){bX.push(b8)}else{if(b8>bZ.line){bX.push(b8+b0)}}}if(cb.length){bX.push(b6.line)}a3=bX;bP(100);bI.push({from:b6.line,to:bZ.line+1,diff:b0});aH={from:b6,to:bZ,text:cb};function b4(cd){return cd<=Math.min(bZ.line,bZ.line+b0)?cd:cd+b0}bt(bV,cc,b4(aO.from.line),b4(aO.to.line));
aC.style.height=(bK.length*bJ()+2*a4())+"px"}function bl(bW,bZ,bY){bZ=af(bZ);if(!bY){bY=bZ}else{bY=af(bY)}bW=n(bW);function bX(b2){if(A(b2,bZ)){return b2}if(!A(bY,b2)){return bV}var b0=b2.line+bW.length-(bY.line-bZ.line)-1;var b1=b2.ch;if(b2.line==bY.line){b1+=bW[bW.length-1].length-(bY.ch-(bY.line==bZ.line?bZ.ch:0))}return{line:b0,ch:b1}}var bV;bx(bW,bZ,bY,function(b0){bV=b0;return{from:bX(aO.from),to:bX(aO.to)}
});return bV}function ah(bV,bW){bx(n(bV),aO.from,aO.to,function(bX){if(bW=="end"){return{from:bX,to:bX}}else{if(bW=="start"){return{from:aO.from,to:aO.from}}else{return{from:aO.from,to:bX}}}})}function bx(bY,b0,bZ,bV){var bX=bY.length==1?bY[0].length+b0.ch:bY[bY.length-1].length;var bW=bV({line:b0.line+bY.length-1,ch:bX});bf(b0,bZ,bY,bW.from,bW.to)}function a5(b0,bZ){var bW=b0.line,bV=bZ.line;if(bW==bV){return bK[bW].text.slice(b0.ch,bZ.ch)
}var bY=[bK[bW].text.slice(b0.ch)];for(var bX=bW+1;bX<bV;++bX){bY.push(bK[bX].text)}bY.push(bK[bV].text.slice(0,bZ.ch));return bY.join("\n")}function bB(){return a5(aO.from,aO.to)}var aV=false;function bv(){if(aV){return}aE.set(2000,function(){U();bE();if(i){bv()}aI()})}function bF(bX){var bV=false;aV=true;function bW(){U();var bY=bE();if(bY=="moved"&&bX){G[bX]=true}if(!bY&&!bV){bV=true;aE.set(80,bW)
}else{aV=false;bv()}aI()}aE.set(20,bW)}function bE(){if(bG){return}var b2=false,ca=bQ.value,cc=H(bQ);if(!cc){return false}var b2=S.text!=ca,b4=bu;var b3=b2||cc.start!=S.start||cc.end!=(b4?S.start:S.end);if(!b3&&!b4){return false}if(b2){a2=bu=null;if(a9.readOnly){bg=true;return"changed"}}function bZ(ci,cg){var ch=0;for(;;){var cf=ca.indexOf("\n",ch);if(cf==-1||(ca.charAt(cf-1)=="\r"?cf-1:cf)>=ci){return{line:cg,ch:ci-ch}
}++cg;ch=cf+1}}var cb=bZ(cc.start,S.from),bW=bZ(cc.end,S.from);if(b4){var b1=cc.start==b4.anchor?bW:cb;var b5=a2?aO.to:cc.start==b4.anchor?cb:bW;if(aO.inverted=A(b1,b5)){cb=b1;bW=b5}else{bu=null;cb=b5;bW=b1}}if(cb.line==bW.line&&cb.line==aO.from.line&&cb.line==aO.to.line&&!a2){bg=false}if(b2){var b0=0,bY=ca.length,cd=Math.min(bY,S.text.length);var ce,b7=S.from,bX=-1;while(b0<cd&&(ce=ca.charAt(b0))==S.text.charAt(b0)){++b0;
if(ce=="\n"){b7++;bX=b0}}var b8=bX>-1?b0-bX:b0,bV=S.to-1,b6=S.text.length;for(;;){ce=S.text.charAt(b6);if(ca.charAt(bY)!=ce){++bY;++b6;break}if(ce=="\n"){bV--}if(b6<=b0||bY<=b0){break}--bY;--b6}var bX=S.text.lastIndexOf("\n",b6-1),b9=bX==-1?b6:b6-bX-1;bf({line:b7,ch:b8},{line:bV,ch:b9},n(ca.slice(b0,bY)),cb,bW);if(b7!=bV||cb.line!=b7){bg=true}}else{bt(cb,bW)}S.text=ca;S.start=cc.start;S.end=cc.end;
return b2?"changed":b3?"moved":false}function az(){var bY=[];var b0=Math.max(0,aO.from.line-1),bZ=Math.min(bK.length,aO.to.line+2);for(var bX=b0;bX<bZ;++bX){bY.push(bK[bX].text)}bY=bQ.value=bY.join(d);var bW=aO.from.ch,bV=aO.to.ch;for(var bX=b0;bX<aO.from.line;++bX){bW+=d.length+bK[bX].text.length}for(var bX=b0;bX<aO.to.line;++bX){bV+=d.length+bK[bX].text.length}S={text:bY,from:b0,to:bZ,start:bW,end:bV};
b(bQ,bW,bu?bW:bV)}function am(){if(a9.readOnly!="nocursor"){bQ.focus()}}function aT(){var bV=br(aO.inverted?aO.from:aO.to);return bS(bV.x,bV.y,bV.x,bV.yBot)}function bS(bX,b1,bV,b0){var bZ=bj(),b7=a4(),b3=bJ();b1+=b7;b0+=b7;bX+=bZ;bV+=bZ;var b4=aB.clientHeight,bY=aB.scrollTop,bW=false,b6=true;if(b1<bY){aB.scrollTop=Math.max(0,b1-2*b3);bW=true}else{if(b0>bY+b4){aB.scrollTop=b0+b3-b4;bW=true}}var b2=aB.clientWidth,b5=aB.scrollLeft;
if(bX<b5){if(bX<50){bX=0}aB.scrollLeft=Math.max(0,bX-10);bW=true}else{if(bV>b2+b5){aB.scrollLeft=bV+10-b2;bW=true;if(bV>aC.clientWidth){b6=false}}}if(bW&&a9.onScroll){a9.onScroll(bH)}return b6}function bM(){var bV=bJ(),bW=aB.scrollTop-a4();return{from:Math.min(bK.length,Math.max(0,Math.floor(bW/bV))),to:Math.min(bK.length,Math.ceil((bW+aB.clientHeight)/bV))}}function ab(ce){if(!aB.clientWidth){bd=bs=0;
return}var cd=ce===true?[]:[{from:bd,to:bs,domStart:0}];for(var cc=0,b8=ce.length||0;cc<b8;++cc){var b2=ce[cc],b0=[],b3=b2.diff||0;for(var cb=0,b9=cd.length;cb<b9;++cb){var b5=cd[cb];if(b2.to<=b5.from){b0.push({from:b5.from+b3,to:b5.to+b3,domStart:b5.domStart})}else{if(b5.to<=b2.from){b0.push(b5)}else{if(b2.from>b5.from){b0.push({from:b5.from,to:b2.from,domStart:b5.domStart})}if(b2.to<b5.to){b0.push({from:b2.to+b3,to:b5.to+b3,domStart:b5.domStart+(b2.to-b5.from)})
}}}}cd=b0}var bX=bM();var ca=Math.min(bd,Math.max(bX.from-3,0)),bV=Math.min(bK.length,Math.max(bs,bX.to+3)),b1=[],b4=0,bZ=bs-bd,bY=ca,b7=0;for(var cc=0,b8=cd.length;cc<b8;++cc){var b5=cd[cc];if(b5.to<=ca){continue}if(b5.from>=bV){break}if(b5.domStart>b4||b5.from>bY){b1.push({from:bY,to:b5.from,domSize:b5.domStart-b4,domStart:b4});b7+=b5.from-bY}bY=b5.to;b4=b5.domStart+(b5.to-b5.from)}if(b4!=bZ||bY!=bV){b7+=Math.abs(bV-bY);
b1.push({from:bY,to:bV,domSize:bZ-b4,domStart:b4})}if(!b1.length){return}ae.style.display="none";if(b7>(bX.to-bX.from)*0.3){aX(ca=Math.max(bX.from-10,0),bV=Math.min(bX.to+7,bK.length))}else{V(b1)}ae.style.display="";var b6=ca!=bd||bV!=bs||bz!=aB.clientHeight;bd=ca;bs=bV;bi.style.top=(ca*bJ())+"px";if(b6){bz=aB.clientHeight;aC.style.height=(bK.length*bJ()+2*a4())+"px";T()}var bW=aP(aG);aF.style.width=bW>aB.clientWidth?bW+"px":"";
if(ae.childNodes.length!=bs-bd){throw new Error("BAD PATCH! "+JSON.stringify(b1)+" size="+(bs-bd)+" nodes="+ae.childNodes.length)}bA()}function aX(b2,b1){var bY=[],b0={line:b2,ch:0},bZ=A(aO.from,b0)&&!A(aO.to,b0);for(var bX=b2;bX<b1;++bX){var bW=null,bV=null;if(bZ){bW=0;if(aO.to.line==bX){bZ=false;bV=aO.to.ch}}else{if(aO.from.line==bX){if(aO.to.line==bX){bW=aO.from.ch;bV=aO.to.ch}else{bZ=true;bW=aO.from.ch
}}}bY.push(bK[bX].getHTML(bW,bV,true))}ae.innerHTML=bY.join("")}function V(b7){var b8=aO.from.line,b9=aO.to.line,bX=0,b5=w&&bD.createElement("div");for(var b3=0,b4=b7.length;b3<b4;++b3){var b0=b7[b3];var bZ=(b0.to-b0.from)-b0.domSize;var b6=ae.childNodes[b0.domStart+b0.domSize+bX]||null;if(w){for(var b2=Math.max(-bZ,b0.domSize);b2>0;--b2){ae.removeChild(b6?b6.previousSibling:ae.lastChild)}}else{if(bZ){for(var b2=Math.max(0,bZ);
b2>0;--b2){ae.insertBefore(bD.createElement("pre"),b6)}for(var b2=Math.max(0,-bZ);b2>0;--b2){ae.removeChild(b6?b6.previousSibling:ae.lastChild)}}}var bY=ae.childNodes[b0.domStart+bX],b1=b8<b0.from&&b9>=b0.from;for(var b2=b0.from;b2<b0.to;++b2){var bW=null,bV=null;if(b1){bW=0;if(b9==b2){b1=false;bV=aO.to.ch}}else{if(b8==b2){if(b9==b2){bW=aO.from.ch;bV=aO.to.ch}else{b1=true;bW=aO.from.ch}}}if(w){b5.innerHTML=bK[b2].getHTML(bW,bV,true);
ae.insertBefore(b5.firstChild,b6)}else{bY.innerHTML=bK[b2].getHTML(bW,bV,false);bY.className=bK[b2].className||"";bY=bY.nextSibling}}bX+=bZ}}function T(){if(!a9.gutter&&!a9.lineNumbers){return}var bX=bi.offsetHeight,b4=aB.clientHeight;aM.style.height=(bX-b4<2?b4:bX)+"px";var b2=[];for(var b0=bd;b0<Math.max(bs,bd+1);++b0){var b1=bK[b0].gutterMarker;var b3=a9.lineNumbers?b0+a9.firstLineNumber:null;if(b1&&b1.text){b3=b1.text.replace("%N%",b3!=null?b3:"")
}else{if(b3==null){b3="\u00a0"}}b2.push((b1&&b1.style?'<pre class="'+b1.style+'">':"<pre>"),b3,"</pre>")}aM.style.display="none";bO.innerHTML=b2.join("");var bZ=String(bK.length).length,bV=bO.firstChild,bW=p(bV),bY="";while(bW.length+bY.length<bZ){bY+="\u00a0"}if(bY){bV.insertBefore(bD.createTextNode(bY),bV.firstChild)}aM.style.display="";aF.style.marginLeft=aM.offsetWidth+"px"}function bA(){var bX=aO.inverted?aO.from:aO.to,bW=bJ();
var bV=P(bX.line,bX.ch)+"px",bY=(bX.line-bd)*bW+"px";bT.style.top=(bX.line*bW-aB.scrollTop)+"px";if(F(aO.from,aO.to)){aa.style.top=bY;aa.style.left=bV;aa.style.display=""}else{aa.style.display="none"}}function aN(bX,bW){var bV=a2&&af(a2);if(bV){if(A(bV,bX)){bX=bV}else{if(A(bW,bV)){bW=bV}}}bt(bX,bW)}function bt(bZ,bY,bV,bX){if(F(aO.from,bZ)&&F(aO.to,bY)){return}if(A(bY,bZ)){var bW=bY;bY=bZ;bZ=bW}if(F(bZ,bY)){aO.inverted=false
}else{if(F(bZ,aO.to)){aO.inverted=false}else{if(F(bY,aO.from)){aO.inverted=true}}}if(bV==null){bV=aO.from.line;bX=aO.to.line}if(F(bZ,bY)){if(!F(aO.from,aO.to)){bI.push({from:bV,to:bX+1})}}else{if(F(aO.from,aO.to)){bI.push({from:bZ.line,to:bY.line+1})}else{if(!F(bZ,aO.from)){if(bZ.line<bV){bI.push({from:bZ.line,to:Math.min(bY.line,bV)+1})}else{bI.push({from:bV,to:Math.min(bX,bZ.line)+1})}}if(!F(bY,aO.to)){if(bY.line<bX){bI.push({from:Math.max(bV,bZ.line),to:bX+1})
}else{bI.push({from:Math.max(bZ.line,bX),to:bY.line+1})}}}}aO.from=bZ;aO.to=bY;aj=true}function aR(bV,bX,bW){var bY=af({line:bV,ch:bX||0});(bW?aN:bt)(bY,bY)}function aW(bV){return Math.max(0,Math.min(bV,bK.length-1))}function af(bX){if(bX.line<0){return{line:0,ch:0}}if(bX.line>=bK.length){return{line:bK.length-1,ch:bK[bK.length-1].text.length}}var bV=bX.ch,bW=bK[bX.line].text.length;if(bV==null||bV>bW){return{line:bX.line,ch:bW}
}else{if(bV<0){return{line:bX.line,ch:0}}else{return bX}}}function bC(bX){var bV=Math.floor(aB.clientHeight/bJ()),bW=aO.inverted?aO.from:aO.to;aR(bW.line+(Math.max(bV-1,1)*(bX?1:-1)),bW.ch,true)}function bN(bV){var bW=bV?{line:0,ch:0}:{line:bK.length-1,ch:bK[bK.length-1].text.length};aN(bW,bW)}function bn(){var bV=bK.length-1;bt({line:0,ch:0},{line:bV,ch:bK[bV].text.length})}function be(bY){var bW=bK[bY.line].text;
var bX=bY.ch,bV=bY.ch;while(bX>0&&/\w/.test(bW.charAt(bX-1))){--bX}while(bV<bW.length&&/\w/.test(bW.charAt(bV))){++bV}aN({line:bY.line,ch:bX},{line:bY.line,ch:bV})}function aJ(bV){aN({line:bV,ch:0},{line:bV,ch:bK[bV].text.length})}function ax(){ah("\n","end");if(a9.enterMode!="flat"){aq(aO.from.line,a9.enterMode=="keep"?"prev":"smart")}}function aw(bV){a2=null;switch(a9.tabMode){case"default":return false;
case"indent":for(var bW=aO.from.line,bX=aO.to.line;bW<=bX;++bW){aq(bW,"smart")}break;case"classic":if(F(aO.from,aO.to)){if(bV){aq(aO.from.line,"smart")}else{ah("\t","end")}break}case"shift":for(var bW=aO.from.line,bX=aO.to.line;bW<=bX;++bW){aq(bW,bV?"subtract":"add")}break}return true}function aq(bX,b4){if(b4=="smart"){if(!bb.indent){b4="prev"}else{var bV=aD(bX)}}var b5=bK[bX],bZ=b5.indentation(),bW=b5.text.match(/^\s*/)[0],b1;
if(b4=="prev"){if(bX){b1=bK[bX-1].indentation()}else{b1=0}}else{if(b4=="smart"){b1=bb.indent(bV,b5.text.slice(bW.length))}else{if(b4=="add"){b1=bZ+a9.indentUnit}else{if(b4=="subtract"){b1=bZ-a9.indentUnit}}}}b1=Math.max(0,b1);var b3=b1-bZ;if(!b3){if(aO.from.line!=bX&&aO.to.line!=bX){return}var b2=bW}else{var b2="",b0=0;if(a9.indentWithTabs){for(var bY=Math.floor(b1/o);bY;--bY){b0+=o;b2+="\t"}}while(b0<b1){++b0;
b2+=" "}}bl(b2,{line:bX,ch:0},{line:bX,ch:bW.length})}function bk(){bb=l.getMode(a9,a9.mode);for(var bW=0,bV=bK.length;bW<bV;++bW){bK[bW].stateAfter=null}a3=[0];bP()}function N(){var bV=a9.gutter||a9.lineNumbers;aM.style.display=bV?"":"none";if(bV){T()}else{ae.parentNode.style.marginLeft=0}}function Q(b1,b0,bX){b1=af(b1);b0=af(b0);var bV=[];function bZ(b2,b6,b5,b3){var b2=bK[b2],b4=b2.addMark(b6,b5,b3);
b4.line=b2;bV.push(b4)}if(b1.line==b0.line){bZ(b1.line,b1.ch,b0.ch,bX)}else{bZ(b1.line,b1.ch,null,bX);for(var bW=b1.line+1,bY=b0.line;bW<bY;++bW){bZ(bW,0,null,bX)}bZ(b0.line,0,b0.ch,bX)}bI.push({from:b1.line,to:b0.line+1});return function(){var b6,b2;for(var b3=0;b3<bV.length;++b3){var b5=bV[b3],b4=k(bK,b5.line);b5.line.removeMark(b5);if(b4>-1){if(b6==null){b6=b4}b2=b4}}if(b6!=null){bI.push({from:b6,to:b2+1})
}}}function ak(bV,bX,bW){if(typeof bV=="number"){bV=bK[aW(bV)]}bV.gutterMarker={text:bX,style:bW};T();return bV}function Z(bV){if(typeof bV=="number"){bV=bK[aW(bV)]}bV.gutterMarker=null;T()}function aK(bV,bW){if(typeof bV=="number"){var bX=bV;bV=bK[aW(bV)]}else{var bX=k(bK,bV);if(bX==-1){return null}}if(bV.className!=bW){bV.className=bW;bI.push({from:bX,to:bX+1})}return bV}function W(bW){if(typeof bW=="number"){var bX=bW;
bW=bK[bW];if(!bW){return null}}else{var bX=k(bK,bW);if(bX==-1){return null}}var bV=bW.gutterMarker;return{line:bX,text:bW.text,markerText:bV&&bV.text,markerClass:bV&&bV.style}}function aP(bV){au.innerHTML="<pre><span>x</span></pre>";au.firstChild.firstChild.firstChild.nodeValue=bV;return au.firstChild.firstChild.offsetWidth||10}function P(bV,bW){if(bW==0){return 0}au.innerHTML="<pre><span>"+bK[bV].getHTML(null,null,false,bW)+"</span></pre>";
return au.firstChild.firstChild.offsetWidth}function a8(b7,b1){if(b1<=0){return 0}var bY=bK[b7],b4=bY.text;function b5(b8){au.innerHTML="<pre><span>"+bY.getHTML(null,null,false,b8)+"</span></pre>";return au.firstChild.firstChild.offsetWidth}var b2=0,b0=0,b3=b4.length,bZ;var bW=Math.min(b3,Math.ceil(b1/aP("x")));for(;;){var bX=b5(bW);if(bX<=b1&&bW<b3){bW=Math.min(b3,Math.ceil(bW*1.2))}else{bZ=bX;b3=bW;
break}}if(b1>bZ){return b3}bW=Math.floor(b3*0.8);bX=b5(bW);if(bX<b1){b2=bW;b0=bX}for(;;){if(b3-b2<=1){return(bZ-b1>b1-b0)?b2:b3}var b6=Math.ceil((b2+b3)/2),bV=b5(b6);if(bV>b1){b3=b6;bZ=bV}else{b2=b6;b0=bV}}}function br(bY,bX){var bW=bJ(),bV=bY.line-(bX?bd:0);return{x:P(bY.line,bY.ch),y:bV*bW,yBot:(bV+1)*bW}}function bq(bX){var bV=br(bX,true),bW=K(aF);return{x:bW.left+bV.x,y:bW.top+bV.y,yBot:bW.top+bV.yBot}
}function bJ(){var bV=ae.childNodes.length;if(bV){return(ae.offsetHeight/bV)||1}au.innerHTML="<pre>x</pre>";return au.firstChild.offsetHeight||1}function a4(){return aF.offsetTop}function bj(){return aF.offsetLeft}function Y(b0,bZ){var bY=K(aB,true),bV=b0.e.clientX,b1=b0.e.clientY;if(!bZ&&(bV-bY.left>aB.clientWidth||b1-bY.top>aB.clientHeight)){return null}var bX=K(aF,true);var bW=bd+Math.floor((b1-bX.top)/bJ());
return af({line:bW,ch:a8(aW(bW),bV-bX.left)})}function al(bW){var b0=Y(bW);if(!b0||window.opera){return}if(F(aO.from,aO.to)||A(b0,aO.from)||!A(b0,aO.to)){aR(b0.line,b0.ch)}var bZ=bQ.style.cssText;bQ.style.cssText="position: fixed; width: 30px; height: 30px; top: "+(bW.pageY()-1)+"px; left: "+(bW.pageX()-1)+"px; z-index: 1000; background: white; border-width: 0; outline: none; overflow: hidden; opacity: .05;";
var bY=bQ.value=bB();am();b(bQ,0,bQ.value.length);bG=true;function bV(){if(bQ.value!=bY){bL(ah)(bQ.value,"end")}bQ.style.cssText=bZ;bG=false;az();bv()}if(t){bW.stop();var bX=j(window,"mouseup",function(){bX();setTimeout(bV,20)},true)}else{setTimeout(bV,50)}}function M(){clearInterval(ad);var bV=true;aa.style.visibility="";ad=setInterval(function(){aa.style.visibility=(bV=!bV)?"":"hidden"},650)}var bR={"(":")>",")":"(<","[":"]>","]":"[<","{":"}>","}":"{<"};
function ap(b1){var bV=aO.inverted?aO.from:aO.to,b3=bK[bV.line],bW=bV.ch-1;var b0=(bW>=0&&bR[b3.text.charAt(bW)])||bR[b3.text.charAt(++bW)];if(!b0){return}var b4=b0.charAt(0),b2=b0.charAt(1)==">",ce=b2?1:-1,b9=b3.styles;for(var cf=bW+1,cb=0,cd=b9.length;cb<cd;cb+=2){if((cf-=b9[cb].length)<=0){var cc=b9[cb+1];break}}var bY=[b3.text.charAt(bW)],b8=/[(){}[\]]/;function b6(cr,cm,cn){if(!cr.text){return
}var cq=cr.styles,cl=b2?0:cr.text.length-1,co;for(var ci=b2?0:cq.length-2,ck=b2?cq.length:-2;ci!=ck;ci+=2*ce){var cp=cq[ci];if(cq[ci+1]!=null&&cq[ci+1]!=cc){cl+=ce*cp.length;continue}for(var ch=b2?0:cp.length-1,cg=b2?cp.length:-1;ch!=cg;ch+=ce,cl+=ce){if(cl>=cm&&cl<cn&&b8.test(co=cp.charAt(ch))){var cj=bR[co];if(cj.charAt(1)==">"==b2){bY.push(co)}else{if(bY.pop()!=cj.charAt(0)){return{pos:cl,match:false}
}else{if(!bY.length){return{pos:cl,match:true}}}}}}}}for(var cb=bV.line,cd=b2?Math.min(cb+50,bK.length):Math.max(-1,cb-50);cb!=cd;cb+=ce){var b3=bK[cb],bZ=cb==bV.line;var b5=b6(b3,bZ&&b2?bW+1:0,bZ&&!b2?bW:b3.text.length);if(b5){var cc=b5.match?"CodeMirror-matchingbracket":"CodeMirror-nonmatchingbracket";var ca=Q({line:bV.line,ch:bW},{line:bV.line,ch:bW+1},cc),bX=Q({line:cb,ch:b5.pos},{line:cb,ch:b5.pos+1},cc);
var b7=bL(function(){ca();bX()});if(b1){setTimeout(b7,800)}else{by=b7}break}}}function aY(b1){var b0,bX;for(var bW=b1,bY=b1-40;bW>bY;--bW){if(bW==0){return 0}var bV=bK[bW-1];if(bV.stateAfter){return bW}var bZ=bV.indentation();if(bX==null||b0>bZ){bX=bW;b0=bZ}}return bX}function aD(bZ){var bY=aY(bZ),bX=bY&&bK[bY-1].stateAfter;if(!bX){bX=y(bb)}else{bX=h(bb,bX)}for(var bW=bY;bW<bZ;++bW){var bV=bK[bW];bV.highlight(bb,bX);
bV.stateAfter=h(bb,bX)}if(!bK[bZ].stateAfter){a3.push(bZ)}return bX}function a7(bZ,bW){var bY=aD(bZ);for(var bX=bZ;bX<bW;++bX){var bV=bK[bX];bV.highlight(bb,bY);bV.stateAfter=h(bb,bY)}}function a1(){var b0=+new Date+a9.workTime;var b4=a3.length;while(a3.length){if(!bK[bd].stateAfter){var bX=bd}else{var bX=a3.pop()}if(bX>=bK.length){continue}var bW=aY(bX),bV=bW&&bK[bW-1].stateAfter;if(bV){bV=h(bb,bV)
}else{bV=y(bb)}var bZ=0;for(var b3=bW,bY=bK.length;b3<bY;++b3){var b5=bK[b3],b1=b5.stateAfter;if(+new Date>b0){a3.push(b3);bP(a9.workDelay);bI.push({from:bX,to:b3});return}var b2=b5.highlight(bb,bV);b5.stateAfter=h(bb,bV);if(b2||!b1){bZ=0}else{if(++bZ>3){break}}}bI.push({from:bX,to:b3})}if(b4&&a9.onHighlightComplete){a9.onHighlightComplete(bH)}}function bP(bV){if(!a3.length){return}an.set(bV,bL(a1))
}function U(){bg=null;bI=[];aH=aj=false}function aI(){var bW=false;if(aj){bW=!aT()}if(bI.length){ab(bI)}else{if(aj){bA()}}if(bW){aT()}if(aj){M()}if(!bG&&(bg===true||(bg!==false&&aj))){az()}if(aj&&a9.matchBrackets){setTimeout(bL(function(){if(by){by();by=null}ap(false)}),20)}var bV=aH;if(aj&&a9.onCursorActivity){a9.onCursorActivity(bH)}if(bV&&a9.onChange&&bH){a9.onChange(bH,bV)}}var at=0;function bL(bV){return function(){if(!at++){U()
}try{var bW=bV.apply(this,arguments)}finally{if(!--at){aI()}}return bW}}function av(bX,bZ,bW){this.atOccurrence=false;if(bW==null){bW=typeof bX=="string"&&bX==bX.toLowerCase()}if(bZ&&typeof bZ=="object"){bZ=af(bZ)}else{bZ={line:0,ch:0}}this.pos={from:bZ,to:bZ};if(typeof bX!="string"){this.matches=function(b2,b6){if(b2){var b0=bK[b6.line].text.slice(0,b6.ch),b1=b0.match(bX),b5=0;while(b1){var b3=b0.indexOf(b1[0]);
b5+=b3;b0=b0.slice(b3+1);var b4=b0.match(bX);if(b4){b1=b4}else{break}b5++}}else{var b0=bK[b6.line].text.slice(b6.ch),b1=b0.match(bX),b5=b1&&b6.ch+b0.indexOf(b1[0])}if(b1){return{from:{line:b6.line,ch:b5},to:{line:b6.line,ch:b5+b1[0].length},match:b1}}}}else{if(bW){bX=bX.toLowerCase()}var bV=bW?function(b0){return b0.toLowerCase()}:function(b0){return b0};var bY=bX.split("\n");if(bY.length==1){this.matches=function(b3,b4){var b1=bV(bK[b4.line].text),b0=bX.length,b2;
if(b3?(b4.ch>=b0&&(b2=b1.lastIndexOf(bX,b4.ch-b0))!=-1):(b2=b1.indexOf(bX,b4.ch))!=-1){return{from:{line:b4.line,ch:b2},to:{line:b4.line,ch:b2+b0}}}}}else{this.matches=function(b5,b7){var b6=b7.line,b8=(b5?bY.length-1:0),b3=bY[b8],b9=bV(bK[b6].text);var b4=(b5?b9.indexOf(b3)+b3.length:b9.lastIndexOf(b3));if(b5?b4>=b7.ch||b4!=b3.length:b4<=b7.ch||b4!=b9.length-b3.length){return}for(;;){if(b5?!b6:b6==bK.length-1){return
}b9=bV(bK[b6+=b5?-1:1].text);b3=bY[b5?--b8:++b8];if(b8>0&&b8<bY.length-1){if(b9!=b3){return}else{continue}}var b2=(b5?b9.lastIndexOf(b3):b9.indexOf(b3)+b3.length);if(b5?b2!=b9.length-b3.length:b2!=b3.length){return}var b0={line:b7.line,ch:b4},b1={line:b6,ch:b2};return{from:b5?b1:b0,to:b5?b0:b1}}}}}}av.prototype={findNext:function(){return this.find(false)},findPrevious:function(){return this.find(true)
},find:function(bW){var bV=this,bY=af(bW?this.pos.from:this.pos.to);function bX(bZ){var b0={line:bZ,ch:0};bV.pos={from:b0,to:b0};bV.atOccurrence=false;return false}for(;;){if(this.pos=this.matches(bW,bY)){this.atOccurrence=true;return this.pos.match||true}if(bW){if(!bY.line){return bX(0)}bY={line:bY.line-1,ch:bK[bY.line-1].text.length}}else{if(bY.line==bK.length-1){return bX(bK.length)}bY={line:bY.line+1,ch:0}
}}},from:function(){if(this.atOccurrence){return B(this.pos.from)}},to:function(){if(this.atOccurrence){return B(this.pos.to)}}};for(var bp in C){if(C.propertyIsEnumerable(bp)&&!bH.propertyIsEnumerable(bp)){bH[bp]=C[bp]}}return bH}l.defaults={value:"",mode:null,theme:"default",indentUnit:2,indentWithTabs:false,tabMode:"classic",enterMode:"indent",electricChars:true,onKeyEvent:null,lineNumbers:false,gutter:false,firstLineNumber:1,readOnly:false,onChange:null,onCursorActivity:null,onGutterClick:null,onHighlightComplete:null,onFocus:null,onBlur:null,onScroll:null,matchBrackets:false,workTime:100,workDelay:200,undoDepth:40,tabindex:null,document:window.document};
var I={},x={};l.defineMode=function(i,L){if(!l.defaults.mode&&i!="null"){l.defaults.mode=i}I[i]=L};l.defineMIME=function(L,i){x[L]=i};l.getMode=function(M,i){if(typeof i=="string"&&x.hasOwnProperty(i)){i=x[i]}if(typeof i=="string"){var O=i,L={}}else{if(i!=null){var O=i.name,L=i}}var N=I[O];if(!N){if(window.console){console.warn("No mode "+O+" found, falling back to plain text.")}return l.getMode(M,"text/plain")
}return N(M,L||{})};l.listModes=function(){var L=[];for(var i in I){if(I.propertyIsEnumerable(i)){L.push(i)}}return L};l.listMIMEs=function(){var L=[];for(var i in x){if(x.propertyIsEnumerable(i)){L.push(i)}}return L};var C={};l.defineExtension=function(i,L){C[i]=L};l.fromTextArea=function(L,N){if(!N){N={}}N.value=L.value;if(!N.tabindex&&L.tabindex){N.tabindex=L.tabindex}function P(){L.value=i.getValue()
}if(L.form){var O=j(L.form,"submit",P,true);if(typeof L.form.submit=="function"){var M=L.form.submit;function Q(){P();L.form.submit=M;L.form.submit();L.form.submit=Q}L.form.submit=Q}}L.style.display="none";var i=l(function(R){L.parentNode.insertBefore(R,L.nextSibling)},N);i.save=P;i.toTextArea=function(){P();L.parentNode.removeChild(i.getWrapperElement());L.style.display="";if(L.form){O();if(typeof L.form.submit=="function"){L.form.submit=M
}}};return i};function h(N,i){if(i===true){return i}if(N.copyState){return N.copyState(i)}var M={};for(var O in i){var L=i[O];if(L instanceof Array){L=L.concat([])}M[O]=L}return M}l.startState=y;function y(M,L,i){return M.startState?M.startState(L,i):true}l.copyState=h;function a(i){this.pos=this.start=0;this.string=i}a.prototype={eol:function(){return this.pos>=this.string.length},sol:function(){return this.pos==0
},peek:function(){return this.string.charAt(this.pos)},next:function(){if(this.pos<this.string.length){return this.string.charAt(this.pos++)}},eat:function(i){var M=this.string.charAt(this.pos);if(typeof i=="string"){var L=M==i}else{var L=M&&(i.test?i.test(M):i(M))}if(L){++this.pos;return M}},eatWhile:function(i){var L=this.start;while(this.eat(i)){}return this.pos>L},eatSpace:function(){var i=this.pos;
while(/[\s\u00a0]/.test(this.string.charAt(this.pos))){++this.pos}return this.pos>i},skipToEnd:function(){this.pos=this.string.length},skipTo:function(i){var L=this.string.indexOf(i,this.pos);if(L>-1){this.pos=L;return true}},backUp:function(i){this.pos-=i},column:function(){return g(this.string,this.start)},indentation:function(){return g(this.string)},match:function(N,L,i){if(typeof N=="string"){function O(P){return i?P.toLowerCase():P
}if(O(this.string).indexOf(O(N),this.pos)==this.pos){if(L!==false){this.pos+=N.length}return true}}else{var M=this.string.slice(this.pos).match(N);if(M&&L!==false){this.pos+=M[0].length}return M}},current:function(){return this.string.slice(this.start,this.pos)}};l.StringStream=a;function c(L,i){this.styles=i||[L,null];this.stateAfter=null;this.text=L;this.marked=this.gutterMarker=this.className=null
}c.prototype={replace:function(Q,R,U){var V=[],O=this.marked;J(0,Q,this.styles,V);if(U){V.push(U,null)}J(R,this.text.length,this.styles,V);this.styles=V;this.text=this.text.slice(0,Q)+U+this.text.slice(R);this.stateAfter=null;if(O){var S=U.length-(R-Q),M=this.text.length;function P(i){return i<=Math.min(R,R+S)?i:i+S}for(var N=0;N<O.length;++N){var L=O[N],T=false;if(L.from>=M){T=true}else{L.from=P(L.from);
if(L.to!=null){L.to=P(L.to)}}if(T||L.from>=L.to){O.splice(N,1);N--}}}},split:function(M,L){var i=[L,null];J(M,this.text.length,this.styles,i);return new c(L+this.text.slice(M),i)},addMark:function(O,N,L){var i=this.marked,M={from:O,to:N,style:L};if(this.marked==null){this.marked=[]}this.marked.push(M);this.marked.sort(function(Q,P){return Q.from-P.from});return M},removeMark:function(N){var L=this.marked;
if(!L){return}for(var M=0;M<L.length;++M){if(L[M]==N){L.splice(M,1);break}}},highlight:function(P,L){var R=new a(this.text),T=this.styles,Q=0;var O=false,M=T[0],S;if(this.text==""&&P.blankLine){P.blankLine(L)}while(!R.eol()){var i=P.token(R,L);var N=this.text.slice(R.start,R.pos);R.start=R.pos;if(Q&&T[Q-1]==i){T[Q-2]+=N}else{if(N){if(!O&&(T[Q+1]!=i||(Q&&T[Q-2]!=S))){O=true}T[Q++]=N;T[Q++]=i;S=M;M=T[Q]
}}if(R.pos>5000){T[Q++]=this.text.slice(R.pos);T[Q++]=null;break}}if(T.length!=Q){T.length=Q;O=true}if(Q&&T[Q-2]!=S){O=true}return O||(T.length<5&&this.text.length<10)},getTokenAt:function(P,N,M){var i=this.text,O=new a(i);while(O.pos<M&&!O.eol()){O.start=O.pos;var L=P.token(O,N)}return{start:O.start,end:O.pos,string:O.current(),className:L||null,state:N}},indentation:function(){return g(this.text)
},getHTML:function(X,ab,O,Z){var R=[];if(O){R.push(this.className?'<pre class="'+this.className+'">':"<pre>")}function ac(ak,i){if(!ak){return}if(i){R.push('<span class="cm-',i,'">',u(ak),"</span>")}else{R.push(u(ak))}}var W=this.styles,P=this.text,V=this.marked;if(X==ab){X=null}var ae=P.length;if(Z!=null){ae=Math.min(Z,ae)}if(!P&&Z==null){ac(" ",X!=null&&ab==null?"CodeMirror-selected":null)}else{if(!V&&X==null){for(var ad=0,S=0;
S<ae;ad+=2){var Y=W[ad],aa=Y.length;if(S+aa>ae){Y=Y.slice(0,ae-S)}S+=aa;ac(Y,W[ad+1])}}else{var N=0,ad=0,U="",af,ai=0;var ag=-1,Q=null;function ah(){if(V){ag+=1;Q=(ag<V.length)?V[ag]:null}}ah();while(N<ae){var T=ae;var aj="";if(X!=null){if(X>N){T=X}else{if(ab==null||ab>N){aj=" CodeMirror-selected";if(ab!=null){T=Math.min(T,ab)}}}}while(Q&&Q.to!=null&&Q.to<=N){ah()}if(Q){if(Q.from>N){T=Math.min(T,Q.from)
}else{aj+=" "+Q.style;if(Q.to!=null){T=Math.min(T,Q.to)}}}for(;;){var M=N+U.length;var L=af;if(aj){L=af?af+aj:aj}ac(M>T?U.slice(0,T-N):U,L);if(M>=T){U=U.slice(T-N);N=T;break}N=M;U=W[ad++];af=W[ad++]}}if(X!=null&&ab==null){ac(" ","CodeMirror-selected")}}}if(O){R.push("</pre>")}return R.join("")}};function J(R,S,L,T){for(var P=0,Q=0,M=0;Q<S;P+=2){var N=L[P],O=Q+N.length;if(M==0){if(O>R){T.push(N.slice(R-Q,Math.min(N.length,S-Q)),L[P+1])
}if(O>=R){M=1}}else{if(M==1){if(O>S){T.push(N.slice(0,S-Q),L[P+1])}else{T.push(N,L[P+1])}}}Q=O}}function f(){this.time=0;this.done=[];this.undone=[]}f.prototype={addChange:function(S,N,L){this.undone.length=0;var R=+new Date,P=this.done[this.done.length-1];if(R-this.time>400||!P||P.start>S+N||P.start+P.added<S-P.added+P.old.length){this.done.push({start:S,added:N,old:L})}else{var O=0;if(S<P.start){for(var M=P.start-S-1;
M>=0;--M){P.old.unshift(L[M])}P.added+=P.start-S;P.start=S}else{if(P.start<S){O=S-P.start;N+=O}}for(var M=P.added-O,Q=L.length;M<Q;++M){P.old.push(L[M])}if(P.added<N){P.added=N}}this.time=R}};function D(){if(this.preventDefault){this.preventDefault();this.stopPropagation()}else{this.returnValue=false;this.cancelBubble=true}}function s(i){if(!i.stop){i.stop=D}return i}function v(i){this.e=i}v.prototype={stop:function(){D.call(this.e)
},target:function(){return this.e.target||this.e.srcElement},button:function(){if(this.e.which){return this.e.which}else{if(this.e.button&1){return 1}else{if(this.e.button&2){return 3}else{if(this.e.button&4){return 2}}}}},pageX:function(){if(this.e.pageX!=null){return this.e.pageX}var i=this.target().ownerDocument;return this.e.clientX+i.body.scrollLeft+i.documentElement.scrollLeft},pageY:function(){if(this.e.pageY!=null){return this.e.pageY
}var i=this.target().ownerDocument;return this.e.clientY+i.body.scrollTop+i.documentElement.scrollTop}};function j(N,M,L,i){function O(P){L(new v(P||window.event))}if(typeof N.addEventListener=="function"){N.addEventListener(M,O,false);if(i){return function(){N.removeEventListener(M,O,false)}}}else{N.attachEvent("on"+M,O);if(i){return function(){N.detachEvent("on"+M,O)}}}}function m(){this.id=null}m.prototype={set:function(i,L){clearTimeout(this.id);
this.id=setTimeout(L,i)}};var w=(function(){var i=document.createElement("pre");i.innerHTML=" ";return !i.innerHTML})();var t=/gecko\/\d{7}/i.test(navigator.userAgent);var q=/MSIE \d/.test(navigator.userAgent);var e=/Apple Computer/.test(navigator.vendor);var d="\n";(function(){var i=document.createElement("textarea");i.value="foo\nbar";if(i.value.indexOf("\r")>-1){d="\r\n"}}());var o=8;var r=/Mac/.test(navigator.platform);
var G={};for(var E=35;E<=40;++E){G[E]=G["c"+E]=true}function g(M,L){if(L==null){L=M.search(/[^\s\u00a0]/);if(L==-1){L=M.length}}for(var N=0,O=0;N<L;++N){if(M.charAt(N)=="\t"){O+=o-(O%o)}else{++O}}return O}function K(M,L){var P=M.ownerDocument.body;var i=0,R=0,O=false;for(var Q=M;Q;Q=Q.offsetParent){i+=Q.offsetLeft;R+=Q.offsetTop;if(Q==P){O=true}}var N=L&&O?null:P;for(var Q=M.parentNode;Q!=N;Q=Q.parentNode){if(Q.scrollLeft!=null){i-=Q.scrollLeft;
R-=Q.scrollTop}}return{left:i,top:R}}function p(i){return i.textContent||i.innerText||i.nodeValue||""}function F(L,i){return L.line==i.line&&L.ch==i.ch}function A(L,i){return L.line<i.line||(L.line==i.line&&L.ch<i.ch)}function B(i){return{line:i.line,ch:i.ch}}function u(i){return i.replace(/[<>&]/g,function(L){return L=="&"?"&amp;":L=="<"?"&lt;":"&gt;"})}l.htmlEscape=u;function z(O,N){if(!N){return O?O.length:0
}if(!O){return N.length}for(var M=O.length,L=N.length;M>=0&&L>=0;--M,--L){if(O.charAt(M)!=N.charAt(L)){break}}return L+1}function k(O,L){if(O.indexOf){return O.indexOf(L)}for(var M=0,N=O.length;M<N;++M){if(O[M]==L){return M}}return -1}if("\n\nb".split(/\n/).length!=3){var n=function(M){var N=0,L,i=[];while((L=M.indexOf("\n",N))>-1){i.push(M.slice(N,M.charAt(L-1)=="\r"?L-1:L));N=L+1}i.push(M.slice(N));
return i}}else{var n=function(i){return i.split(/\r?\n/)}}l.splitLines=n;if(window.getSelection){var H=function(L){try{return{start:L.selectionStart,end:L.selectionEnd}}catch(i){return null}};if(e){var b=function(L,M,i){if(M==i){L.setSelectionRange(M,i)}else{L.setSelectionRange(M,i-1);window.getSelection().modify("extend","forward","character")}}}else{var b=function(M,N,i){try{M.setSelectionRange(N,i)
}catch(L){}}}}else{var H=function(N){try{var R=N.ownerDocument.selection.createRange()}catch(T){return null}if(!R||R.parentElement()!=N){return null}var M=N.value,S=M.length,U=N.createTextRange();U.moveToBookmark(R.getBookmark());var P=N.createTextRange();P.collapse(false);if(U.compareEndPoints("StartToEnd",P)>-1){return{start:S,end:S}}var L=-U.moveStart("character",-S);for(var Q=M.indexOf("\r");Q>-1&&Q<L;
Q=M.indexOf("\r",Q+1),L++){}if(U.compareEndPoints("EndToEnd",P)>-1){return{start:L,end:S}}var O=-U.moveEnd("character",-S);for(var Q=M.indexOf("\r");Q>-1&&Q<O;Q=M.indexOf("\r",Q+1),O++){}return{start:L,end:O}};var b=function(P,R,M){var N=P.createTextRange();N.collapse(true);var L=N.duplicate();var O=0,i=P.value;for(var Q=i.indexOf("\n");Q>-1&&Q<R;Q=i.indexOf("\n",Q+1)){++O}N.move("character",R-O);for(;
Q>-1&&Q<M;Q=i.indexOf("\n",Q+1)){++O}L.move("character",M-O);N.setEndPoint("EndToEnd",L);N.select()}}l.defineMode("null",function(){return{token:function(i){i.skipToEnd()}}});l.defineMIME("text/plain","null");return l})();CodeMirror.runMode=function(h,d,n){var g=CodeMirror.getMode({indentUnit:2},d);var k=n.nodeType==1;if(k){var c=n,l=[];n=function(e,i){if(e=="\n"){l.push("<br>")}else{if(i){l.push('<span class="cm-'+CodeMirror.htmlEscape(i)+'">'+CodeMirror.htmlEscape(e)+"</span>")}else{l.push(CodeMirror.htmlEscape(e))}}}}var o=CodeMirror.splitLines(h),b=CodeMirror.startState(g);for(var f=0,j=o.length;f<j;++f){if(f){n("\n")
}var m=new CodeMirror.StringStream(o[f]);while(!m.eol()){var a=g.token(m,b);n(m.current(),a);m.start=m.pos}}if(k){c.innerHTML=l.join("")}};CodeMirror.overlayParser=function(b,a,c){return{startState:function(){return{base:CodeMirror.startState(b),overlay:CodeMirror.startState(a),basePos:0,baseCur:null,overlayPos:0,overlayCur:null}},copyState:function(d){return{base:CodeMirror.copyState(b,d.base),overlay:CodeMirror.copyState(a,d.overlay),basePos:d.basePos,baseCur:null,overlayPos:d.overlayPos,overlayCur:null}},token:function(e,d){if(e.start==d.basePos){d.baseCur=b.token(e,d.base);
d.basePos=e.pos}if(e.start==d.overlayPos){e.pos=e.start;d.overlayCur=a.token(e,d.overlay);d.overlayPos=e.pos}e.pos=Math.min(d.basePos,d.overlayPos);if(e.eol()){d.basePos=d.overlayPos=0}if(d.overlayCur==null){return d.baseCur}if(d.baseCur!=null&&c){return d.baseCur+" "+d.overlayCur}else{return d.overlayCur}},indent:function(e,d){return b.indent(e.base,d)},electricChars:b.electricChars}};CodeMirror.defineMode("clike",function(p,d){var k=p.indentUnit,f=d.keywords,h=d.useCPP,i=d.multiLineStrings,n=d.$vars,b=d.atAnnotations;var g=/[+\-*&%=<>!?|]/;function l(u,t,s){t.tokenize=s;return s(u,t)}var a;function q(t,s){a=t;return s}function r(u,t){var s=u.next();if(s=='"'||s=="'"){return l(u,t,e(s))}else{if(/[\[\]{}\(\),;\:\.]/.test(s)){return q(s)}else{if(s=="#"&&h&&t.startOfLine){u.skipToEnd();
return q("directive","meta")}else{if(/\d/.test(s)){u.eatWhile(/[\w\.]/);return q("number","number")}else{if(s=="/"){if(u.eat("*")){return l(u,t,j)}else{if(u.eat("/")){u.skipToEnd();return q("comment","comment")}else{u.eatWhile(g);return q("operator")}}}else{if(g.test(s)){u.eatWhile(g);return q("operator")}else{if(b&&s=="@"){u.eatWhile(/[\w\$_]/);return q("annotation","meta")}else{if(n&&s=="$"){u.eatWhile(/[\w\$_]/);
return q("word","variable")}else{u.eatWhile(/[\w\$_]/);if(f&&f.propertyIsEnumerable(u.current())){return q("keyword","keyword")}return q("word")}}}}}}}}}function e(s){return function(x,v){var w=false,u,t=false;while((u=x.next())!=null){if(u==s&&!w){t=true;break}w=!w&&u=="\\"}if(t||!(w||i)){v.tokenize=r}return q("string","string")}}function j(v,u){var s=false,t;while(t=v.next()){if(t=="/"&&s){u.tokenize=r;
break}s=(t=="*")}return q("comment","comment")}function m(w,t,s,v,u){this.indented=w;this.column=t;this.type=s;this.align=v;this.prev=u}function c(u,s,t){return u.context=new m(u.indented,s,t,null,u.context)}function o(s){return s.context=s.context.prev}return{startState:function(s){return{tokenize:r,context:new m((s||0)-k,0,"top",false),indented:0,startOfLine:true}},token:function(v,u){var s=u.context;
if(v.sol()){if(s.align==null){s.align=false}u.indented=v.indentation();u.startOfLine=true}if(v.eatSpace()){return null}var t=u.tokenize(v,u);if(a=="comment"){return t}if(s.align==null){s.align=true}if((a==";"||a==":")&&s.type=="statement"){o(u)}else{if(a=="{"){c(u,v.column(),"}")}else{if(a=="["){c(u,v.column(),"]")}else{if(a=="("){c(u,v.column(),")")}else{if(a=="}"){if(s.type=="statement"){s=o(u)}if(s.type=="}"){s=o(u)
}if(s.type=="statement"){s=o(u)}}else{if(a==s.type){o(u)}else{if(s.type=="}"||s.type=="top"){c(u,v.column(),"statement")}}}}}}}u.startOfLine=false;return t},indent:function(w,t){if(w.tokenize!=r){return 0}var v=t&&t.charAt(0),s=w.context,u=v==s.type;if(s.type=="statement"){return s.indented+(v=="{"?0:k)}else{if(s.align){return s.column+(u?0:1)}else{return s.indented+(u?0:k)}}},electricChars:"{}"}});
(function(){function b(f){var d={},e=f.split(" ");for(var c=0;c<e.length;++c){d[e[c]]=true}return d}var a="auto if break int case long char register continue return default short do sizeof double static else struct entry switch extern typedef float union for unsigned goto while enum void const signed volatile";CodeMirror.defineMIME("text/x-csrc",{name:"clike",useCPP:true,keywords:b(a)});CodeMirror.defineMIME("text/x-c++src",{name:"clike",useCPP:true,keywords:b(a+" asm dynamic_cast namespace reinterpret_cast try bool explicit new static_cast typeid catch false operator template typename class friend private this using const_cast inline public throw virtual delete mutable protected true wchar_t")});
CodeMirror.defineMIME("text/x-java",{name:"clike",atAnnotations:true,keywords:b("abstract assert boolean break byte case catch char class const continue default do double else enum extends false final finally float for goto if implements import instanceof int interface long native new null package private protected public return short static strictfp super switch synchronized this throw throws transient true try void volatile while")})
}());CodeMirror.defineMode("css",function(e){var d=e.indentUnit,f;function c(i,j){f=j;return i}function h(k,j){var i=k.next();if(i=="@"){k.eatWhile(/\w/);return c("meta",k.current())}else{if(i=="/"&&k.eat("*")){j.tokenize=a;return a(k,j)}else{if(i=="<"&&k.eat("!")){j.tokenize=b;return b(k,j)}else{if(i=="="){c(null,"compare")}else{if((i=="~"||i=="|")&&k.eat("=")){return c(null,"compare")}else{if(i=='"'||i=="'"){j.tokenize=g(i);
return j.tokenize(k,j)}else{if(i=="#"){k.eatWhile(/\w/);return c("atom","hash")}else{if(i=="!"){k.match(/^\s*\w*/);return c("keyword","important")}else{if(/\d/.test(i)){k.eatWhile(/[\w.%]/);return c("number","unit")}else{if(/[,.+>*\/]/.test(i)){return c(null,"select-op")}else{if(/[;{}:\[\]]/.test(i)){return c(null,i)}else{k.eatWhile(/[\w\\\-_]/);return c("variable","variable")}}}}}}}}}}}}function a(l,k){var i=false,j;
while((j=l.next())!=null){if(i&&j=="/"){k.tokenize=h;break}i=(j=="*")}return c("comment","comment")}function b(l,k){var j=0,i;while((i=l.next())!=null){if(j>=2&&i==">"){k.tokenize=h;break}j=(i=="-")?j+1:0}return c("comment","comment")}function g(i){return function(m,k){var l=false,j;while((j=m.next())!=null){if(j==i&&!l){break}l=!l&&j=="\\"}if(!l){k.tokenize=h}return c("string","string")}}return{startState:function(i){return{tokenize:h,baseIndent:i||0,stack:[]}
},token:function(l,k){if(l.eatSpace()){return null}var j=k.tokenize(l,k);var i=k.stack[k.stack.length-1];if(f=="hash"&&i=="rule"){j="atom"}else{if(j=="variable"){if(i=="rule"){j="number"}else{if(!i||i=="@media{"){j="tag"}}}}if(i=="rule"&&/^[\{\};]$/.test(f)){k.stack.pop()}if(f=="{"){if(i=="@media"){k.stack[k.stack.length-1]="@media{"}else{k.stack.push("{")}}else{if(f=="}"){k.stack.pop()}else{if(f=="@media"){k.stack.push("@media")
}else{if(i=="{"&&f!="comment"){k.stack.push("rule")}}}}return j},indent:function(j,i){var k=j.stack.length;if(/^\}/.test(i)){k-=j.stack[j.stack.length-1]=="rule"?2:1}return j.baseIndent+k*d},electricChars:"}"}});CodeMirror.defineMIME("text/css","css");CodeMirror.defineMode("diff",function(){return{token:function(b){var a=b.next();b.skipToEnd();if(a=="+"){return"plus"}if(a=="-"){return"minus"}if(a=="@"){return"rangeinfo"}}}});CodeMirror.defineMIME("text/x-diff","diff");CodeMirror.defineMode("htmlmixed",function(b,d){var a=CodeMirror.getMode(b,{name:"xml",htmlMode:true});var c=CodeMirror.getMode(b,"javascript");var i=CodeMirror.getMode(b,"css");function e(l,k){var j=a.token(l,k.htmlState);if(j=="tag"&&l.current()==">"&&k.htmlState.context){if(/^script$/i.test(k.htmlState.context.tagName)){k.token=h;k.localState=c.startState(a.indent(k.htmlState,""))}else{if(/^style$/i.test(k.htmlState.context.tagName)){k.token=f;
k.localState=i.startState(a.indent(k.htmlState,""))}}}return j}function g(n,j,k){var m=n.current();var l=m.search(j);if(l>-1){n.backUp(m.length-l)}return k}function h(k,j){if(k.match(/^<\/\s*script\s*>/i,false)){j.token=e;j.curState=null;return e(k,j)}return g(k,/<\/\s*script\s*>/,c.token(k,j.localState))}function f(k,j){if(k.match(/^<\/\s*style\s*>/i,false)){j.token=e;j.localState=null;return e(k,j)
}return g(k,/<\/\s*style\s*>/,i.token(k,j.localState))}return{startState:function(){var j=a.startState();return{token:e,localState:null,htmlState:j}},copyState:function(k){if(k.localState){var j=CodeMirror.copyState(k.token==f?i:c,k.localState)}return{token:k.token,localState:j,htmlState:CodeMirror.copyState(a,k.htmlState)}},token:function(k,j){return j.token(k,j)},indent:function(k,j){if(k.token==e||/^\s*<\//.test(j)){return a.indent(k.htmlState,j)
}else{if(k.token==h){return c.indent(k.localState,j)}else{return i.indent(k.localState,j)}}},electricChars:"/{}:"}});CodeMirror.defineMIME("text/html","htmlmixed");CodeMirror.defineMode("javascript",function(H,L){var v=H.indentUnit;var P=L.json;var b=function(){function V(Y){return{type:Y,style:"keyword"}}var S=V("keyword a"),X=V("keyword b"),W=V("keyword c");var T=V("operator"),U={type:"atom",style:"atom"};return{"if":S,"while":S,"with":S,"else":X,"do":X,"try":X,"finally":X,"return":W,"break":W,"continue":W,"new":W,"delete":W,"throw":W,"var":V("var"),"function":V("function"),"catch":V("catch"),"for":V("for"),"switch":V("switch"),"case":V("case"),"default":V("default"),"in":T,"typeof":T,"instanceof":T,"true":U,"false":U,"null":U,"undefined":U,"NaN":U,"Infinity":U}
}();var M=/[+\-*&%=<>!?|]/;function Q(U,T,S){T.tokenize=S;return S(U,T)}function h(V,S){var U=false,T;while((T=V.next())!=null){if(T==S&&!U){return false}U=!U&&T=="\\"}return U}var R,p;function A(U,T,S){R=U;p=S;return T}function l(W,U){var S=W.next();if(S=='"'||S=="'"){return Q(W,U,z(S))}else{if(/[\[\]{}\(\),;\:\.]/.test(S)){return A(S)}else{if(S=="0"&&W.eat(/x/i)){W.eatWhile(/[\da-f]/i);return A("number","atom")
}else{if(/\d/.test(S)){W.match(/^\d*(?:\.\d*)?(?:e[+\-]?\d+)?/);return A("number","atom")}else{if(S=="/"){if(W.eat("*")){return Q(W,U,f)}else{if(W.eat("/")){W.skipToEnd();return A("comment","comment")}else{if(U.reAllowed){h(W,"/");W.eatWhile(/[gimy]/);return A("regexp","string")}else{W.eatWhile(M);return A("operator",null,W.current())}}}}else{if(M.test(S)){W.eatWhile(M);return A("operator",null,W.current())
}else{W.eatWhile(/[\w\$_]/);var V=W.current(),T=b.propertyIsEnumerable(V)&&b[V];return T?A(T.type,T.style,V):A("variable","variable",V)}}}}}}}function z(S){return function(U,T){if(!h(U,S)){T.tokenize=l}return A("string","string")}}function f(V,U){var S=false,T;while(T=V.next()){if(T=="/"&&S){U.tokenize=l;break}S=(T=="*")}return A("comment","comment")}var k={atom:true,number:true,variable:true,string:true,regexp:true};
function t(X,T,S,W,U,V){this.indented=X;this.column=T;this.type=S;this.prev=U;this.info=V;if(W!=null){this.align=W}}function w(U,T){for(var S=U.localVars;S;S=S.next){if(S.name==T){return true}}}function D(W,T,S,V,X){var Y=W.cc;u.state=W;u.stream=X;u.marked=null,u.cc=Y;if(!W.lexical.hasOwnProperty("align")){W.lexical.align=true}while(true){var U=Y.length?Y.pop():P?x:y;if(U(S,V)){while(Y.length&&Y[Y.length-1].lex){Y.pop()()
}if(u.marked){return u.marked}if(S=="variable"&&w(W,V)){return"variable-2"}return T}}}var u={state:null,column:null,marked:null,cc:null};function a(){for(var S=arguments.length-1;S>=0;S--){u.cc.push(arguments[S])}}function F(){a.apply(null,arguments);return true}function m(T){var U=u.state;if(U.context){u.marked="def";for(var S=U.localVars;S;S=S.next){if(S.name==T){return}}U.localVars={name:T,next:U.localVars}
}}var C={name:"this",next:{name:"arguments"}};function s(){if(!u.state.context){u.state.localVars=C}u.state.context={prev:u.state.context,vars:u.state.localVars}}function r(){u.state.localVars=u.state.context.vars;u.state.context=u.state.context.prev}function j(T,U){var S=function(){var V=u.state;V.lexical=new t(V.indented,u.stream.column(),T,null,V.lexical,U)};S.lex=true;return S}function E(){var S=u.state;
if(S.lexical.prev){if(S.lexical.type==")"){S.indented=S.lexical.indented}S.lexical=S.lexical.prev}}E.lex=true;function c(T){return function S(U){if(U==T){return F()}else{if(T==";"){return a()}else{return F(arguments.callee)}}}}function y(S){if(S=="var"){return F(j("vardef"),I,c(";"),E)}if(S=="keyword a"){return F(j("form"),x,y,E)}if(S=="keyword b"){return F(j("form"),y,E)}if(S=="{"){return F(j("}"),n,E)
}if(S==";"){return F()}if(S=="function"){return F(i)}if(S=="for"){return F(j("form"),c("("),j(")"),g,c(")"),E,y,E)}if(S=="variable"){return F(j("stat"),B)}if(S=="switch"){return F(j("form"),x,j("}","switch"),c("{"),n,E,E)}if(S=="case"){return F(x,c(":"))}if(S=="default"){return F(c(":"))}if(S=="catch"){return F(j("form"),s,c("("),q,c(")"),y,E,r)}return a(j("stat"),x,c(";"),E)}function x(S){if(k.hasOwnProperty(S)){return F(K)
}if(S=="function"){return F(i)}if(S=="keyword c"){return F(x)}if(S=="("){return F(j(")"),x,c(")"),E,K)}if(S=="operator"){return F(x)}if(S=="["){return F(j("]"),N(x,"]"),E,K)}if(S=="{"){return F(j("}"),N(o,"}"),E,K)}return F()}function K(S,T){if(S=="operator"&&/\+\+|--/.test(T)){return F(K)}if(S=="operator"){return F(x)}if(S==";"){return}if(S=="("){return F(j(")"),N(x,")"),E,K)}if(S=="."){return F(O,K)
}if(S=="["){return F(j("]"),x,c("]"),E,K)}}function B(S){if(S==":"){return F(E,y)}return a(K,c(";"),E)}function O(S){if(S=="variable"){u.marked="property";return F()}}function o(S){if(S=="variable"){u.marked="property"}if(k.hasOwnProperty(S)){return F(c(":"),x)}}function N(U,S){function T(W){if(W==","){return F(U,T)}if(W==S){return F()}return F(c(S))}return function V(W){if(W==S){return F()}else{return a(U,T)
}}}function n(S){if(S=="}"){return F()}return a(y,n)}function I(S,T){if(S=="variable"){m(T);return F(G)}return F()}function G(S,T){if(T=="="){return F(x,G)}if(S==","){return F(I)}}function g(S){if(S=="var"){return F(I,e)}if(S==";"){return a(e)}if(S=="variable"){return F(J)}return a(e)}function J(S,T){if(T=="in"){return F(x)}return F(K,e)}function e(S,T){if(S==";"){return F(d)}if(T=="in"){return F(x)
}return F(x,c(";"),d)}function d(S){if(S!=")"){F(x)}}function i(S,T){if(S=="variable"){m(T);return F(i)}if(S=="("){return F(j(")"),s,N(q,")"),E,y,r)}}function q(S,T){if(S=="variable"){m(T);return F()}}return{startState:function(S){return{tokenize:l,reAllowed:true,cc:[],lexical:new t((S||0)-v,0,"block",false),localVars:null,context:null,indented:0}},token:function(U,T){if(U.sol()){if(!T.lexical.hasOwnProperty("align")){T.lexical.align=false
}T.indented=U.indentation()}if(U.eatSpace()){return null}var S=T.tokenize(U,T);if(R=="comment"){return S}T.reAllowed=R=="operator"||R=="keyword c"||R.match(/^[\[{}\(,;:]$/);return D(T,S,R,p,U)},indent:function(X,S){if(X.tokenize!=l){return 0}var W=S&&S.charAt(0),U=X.lexical,V=U.type,T=W==V;if(V=="vardef"){return U.indented+4}else{if(V=="form"&&W=="{"){return U.indented}else{if(V=="stat"||V=="form"){return U.indented+v
}else{if(U.info=="switch"&&!T){return U.indented+(/^(?:case|default)\b/.test(S)?v:2*v)}else{if(U.align){return U.column+(T?0:1)}else{return U.indented+(T?0:v)}}}}}},electricChars:":{}"}});CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:true});(function(){function c(g){var e={},f=g.split(" ");for(var d=0;d<f.length;++d){e[f[d]]=true}return e}var a=c("abstract and array as break case catch cfunction class clone const continue declare default do else elseif enddeclare endfor endforeach endif endswitch endwhile extends final for foreach function global goto if implements interface instanceof namespace new or private protected public static switch throw try use var while xor");
var b={name:"clike",keywords:a,multiLineStrings:true,$vars:true};CodeMirror.defineMode("php",function(f,h){var j=CodeMirror.getMode(f,"text/html");var i=CodeMirror.getMode(f,"text/javascript");var g=CodeMirror.getMode(f,"text/css");var d=CodeMirror.getMode(f,b);function e(m,l){if(l.curMode==j){var k=j.token(m,l.curState);if(k=="meta"&&/^<\?/.test(m.current())){l.curMode=d;l.curState=l.php;l.curClose=/^\?>/
}else{if(k=="tag"&&m.current()==">"&&l.curState.context){if(/^script$/i.test(l.curState.context.tagName)){l.curMode=i;l.curState=i.startState(j.indent(l.curState,""));l.curClose=/^<\/\s*script\s*>/i}else{if(/^style$/i.test(l.curState.context.tagName)){l.curMode=g;l.curState=g.startState(j.indent(l.curState,""));l.curClose=/^<\/\s*style\s*>/i}}}}return k}else{if(m.match(l.curClose,false)){l.curMode=j;
l.curState=l.html;l.curClose=null;return e(m,l)}else{return l.curMode.token(m,l.curState)}}}return{startState:function(){var k=j.startState();return{html:k,php:d.startState(),curMode:j,curState:k,curClose:null}},copyState:function(n){var l=n.html,m=CodeMirror.copyState(j,l),p=n.php,k=CodeMirror.copyState(d,p),o;if(n.curState==l){o=m}else{if(n.curState==p){o=k}else{o=CodeMirror.copyState(n.curMode,n.curState)
}}return{html:m,php:k,curMode:n.curMode,curState:o,curClose:n.curClose}},token:e,indent:function(l,k){if((l.curMode!=d&&/^\s*<\//.test(k))||(l.curMode==d&&/^\?>/.test(k))){return j.indent(l.html,k)}return l.curMode.indent(l.curState,k)},electricChars:"/{}:"}});CodeMirror.defineMIME("application/x-httpd-php","php");CodeMirror.defineMIME("text/x-php",b)})();CodeMirror.defineMode("sql",function(c,g){var i=c.indentUnit,h=g.keywords,f=g.functions,j=g.types,e=g.operators,k=g.multiLineStrings;var b=/[+\-*&%=<>!?:\/|]/;function a(r,q,p){q.tokenize=p;return p(r,q)}var n;function m(q,p){n=q;return p}function d(r,q){var p=r.next();if(p=='"'||p=="'"||p=="`"){return a(r,q,o(p))}else{if(/[\[\]{}\(\)\.]/.test(p)){return m(p)}else{if(p==","||p==";"){return"sql-separator"
}else{if(/\d/.test(p)){r.eatWhile(/[\w\.]/);return m("number","sql-number")}else{if(p=="/"){if(r.eat("*")){return a(r,q,l)}else{r.eatWhile(b);return m("operator","sql-operator")}}else{if(p=="-"){if(r.eat("-")){r.skipToEnd();return m("comment","sql-comment")}else{r.eatWhile(b);return m("operator","sql-operator")}}else{if(p=="#"){r.skipToEnd();return m("comment","sql-comment")}else{if(p=="@"||p=="$"){r.eatWhile(/[\w\d\$_]/);
return m("word","sql-var")}else{if(b.test(p)){r.eatWhile(b);return m("operator","sql-operator")}else{if(/[()]/.test(p)){return"sql-punctuation"}else{r.eatWhile(/[\w\$_]/);if(h&&h.propertyIsEnumerable(r.current().toLowerCase())){return m("keyword","sql-keyword")}if(f&&f.propertyIsEnumerable(r.current().toLowerCase())){return m("keyword","sql-function")}if(j&&j.propertyIsEnumerable(r.current().toLowerCase())){return m("keyword","sql-type")
}if(e&&e.propertyIsEnumerable(r.current().toLowerCase())){return m("keyword","sql-operators")}return m("word","sql-word")}}}}}}}}}}}function o(p){return function(v,t){var u=false,s,q=false;while((s=v.next())!=null){if(s==p&&!u){q=true;break}u=!u&&s=="\\"}if(q||!(u||k)){t.tokenize=d}var r=p=="`"?"sql-quoted-word":"sql-literal";return m("string",r)}}function l(s,r){var p=false,q;while(q=s.next()){if(q=="/"&&p){r.tokenize=d;
break}p=(q=="*")}return m("comment","sql-comment")}return{startState:function(p){return{tokenize:d,indented:0,startOfLine:true}},token:function(r,q){if(r.eatSpace()){return null}var p=q.tokenize(r,q);return p},electricChars:")"}});(function(){function d(j){var g={},h=j.split(" ");for(var f=0;f<h.length;++f){g[h[f]]=true}return g}var c="alter grant revoke primary key table start top transaction select update insert delete create describe from into values where join inner left natural and or in not xor like using on order group by asc desc limit offset union all as distinct set commit rollback replace view database separator if exists null truncate status show lock unique having drop procedure begin end delimiter call else leave declare temporary then";
var b="abs acos adddate aes_encrypt aes_decrypt ascii asin atan atan2 avg benchmark bin bit_and bit_count bit_length bit_or cast ceil ceiling char_length character_length coalesce concat concat_ws connection_id conv convert cos cot count curdate current_date current_time current_timestamp current_user curtime database date_add date_format date_sub dayname dayofmonth dayofweek dayofyear decode degrees des_encrypt des_decrypt elt encode encrypt exp export_set extract field find_in_set floor format found_rows from_days from_unixtime get_lock greatest group_unique_users hex ifnull inet_aton inet_ntoa instr interval is_free_lock isnull last_insert_id lcase least left length ln load_file locate log log2 log10 lower lpad ltrim make_set master_pos_wait max md5 mid min mod monthname now nullif oct octet_length ord password period_add period_diff pi position pow power quarter quote radians rand release_lock repeat reverse right round rpad rtrim sec_to_time session_user sha sha1 sign sin soundex space sqrt std stddev strcmp subdate substring substring_index sum sysdate system_user tan time_format time_to_sec to_days trim ucase unique_users unix_timestamp upper user version week weekday yearweek";
var a="bigint binary bit blob bool char character date datetime dec decimal double enum float float4 float8 int int1 int2 int3 int4 int8 integer long longblob longtext mediumblob mediumint mediumtext middleint nchar numeric real set smallint text time timestamp tinyblob tinyint tinytext varbinary varchar year";var e=":= < <= == <> > >= like rlike in xor between";CodeMirror.defineMIME("text/x-sql",{name:"sql",keywords:d(c),functions:d(b),types:d(a),operators:d(e)})
}());CodeMirror.defineMode("xml",function(v,k){var p=v.indentUnit;var u=k.htmlMode?{autoSelfClosers:{br:true,img:true,hr:true,link:true,input:true,meta:true,col:true,frame:true,base:true,area:true},doNotIndent:{pre:true,"!cdata":true},allowUnquoted:true}:{autoSelfClosers:{},doNotIndent:{"!cdata":true},allowUnquoted:false};var a=k.alignCDATA;var f,g;function o(z,y){function w(B){y.tokenize=B;return B(z,y)
}var x=z.next();if(x=="<"){if(z.eat("!")){if(z.eat("[")){if(z.match("CDATA[")){return w(t("atom","]]>"))}else{return null}}else{if(z.match("--")){return w(t("comment","-->"))}else{if(z.match("DOCTYPE")){z.eatWhile(/[\w\._\-]/);return w(t("meta",">"))}else{return null}}}}else{if(z.eat("?")){z.eatWhile(/[\w\._\-]/);y.tokenize=t("meta","?>");return"meta"}else{g=z.eat("/")?"closeTag":"openTag";z.eatSpace();
f="";var A;while((A=z.eat(/[^\s\u00a0=<>\"\'\/?]/))){f+=A}y.tokenize=n;return"tag"}}}else{if(x=="&"){z.eatWhile(/[^;]/);z.eat(";");return"atom"}else{z.eatWhile(/[^&<]/);return null}}}function n(y,x){var w=y.next();if(w==">"||(w=="/"&&y.eat(">"))){x.tokenize=o;g=w==">"?"endTag":"selfcloseTag";return"tag"}else{if(w=="="){g="equals";return null}else{if(/[\'\"]/.test(w)){x.tokenize=j(w);return x.tokenize(y,x)
}else{y.eatWhile(/[^\s\u00a0=<>\"\'\/?]/);return"word"}}}}function j(w){return function(y,x){while(!y.eol()){if(y.next()==w){x.tokenize=n;break}}return"string"}}function t(x,w){return function(z,y){while(!z.eol()){if(z.match(w)){y.tokenize=o;break}z.next()}return x}}var l,h;function b(){for(var w=arguments.length-1;w>=0;w--){l.cc.push(arguments[w])}}function e(){b.apply(null,arguments);return true}function i(w,y){var x=u.doNotIndent.hasOwnProperty(w)||(l.context&&l.context.noIndent);
l.context={prev:l.context,tagName:w,indent:l.indented,startOfLine:y,noIndent:x}}function r(){if(l.context){l.context=l.context.prev}}function d(w){if(w=="openTag"){l.tagName=f;return e(m,c(l.startOfLine))}else{if(w=="closeTag"){r();return e(q)}else{if(w=="string"){if(!l.context||l.context.name!="!cdata"){i("!cdata")}if(l.tokenize==o){r()}return e()}else{return e()}}}}function c(w){return function(x){if(x=="selfcloseTag"||(x=="endTag"&&u.autoSelfClosers.hasOwnProperty(l.tagName.toLowerCase()))){return e()
}if(x=="endTag"){i(l.tagName,w);return e()}return e()}}function q(w){if(w=="endTag"){return e()}return b()}function m(w){if(w=="word"){h="attribute";return e(m)}if(w=="equals"){return e(s,m)}return b()}function s(w){if(w=="word"&&u.allowUnquoted){h="string";return e()}if(w=="string"){return e()}return b()}return{startState:function(){return{tokenize:o,cc:[],indented:0,startOfLine:true,tagName:null,context:null}
},token:function(z,y){if(z.sol()){y.startOfLine=true;y.indented=z.indentation()}if(z.eatSpace()){return null}h=g=f=null;var x=y.tokenize(z,y);if((x||g)&&x!="xml-comment"){l=y;while(true){var w=y.cc.pop()||d;if(w(g||x)){break}}}y.startOfLine=false;return h||x},indent:function(y,w){var x=y.context;if(x&&x.noIndent){return 0}if(a&&/<!\[CDATA\[/.test(w)){return 0}if(x&&/^<\//.test(w)){x=x.prev}while(x&&!x.startOfLine){x=x.prev
}if(x){return x.indent+p}else{return 0}},electricChars:"/"}});CodeMirror.defineMIME("application/xml","xml");CodeMirror.defineMIME("text/html",{name:"xml",htmlMode:true});