tinyMCE.addI18n('es.emotions_dlg',{
title:"Insertar emoticon",
desc:"Emoticones",
cool:"Todo bien",
cry:"Llora",
embarassed:"Verg\u00C3\u0083\u00C2\u00BCenza",
foot_in_mouth:"Pie en la boca",
frown:"Triste",
innocent:"Inocente",
kiss:"Beso",
laughing:"Risa",
money_mouth:"Dinero boca",
sealed:"Sellado",
smile:"Sonrisa",
surprised:"Sorprendido",
tongue_out:"Lengua fuera",
undecided:"Indeciso",
wink:"Gui\u00F1o",
yell:"Enfadado"
});