tinyMCE.addI18n('da.typolinks_dlg',{
page:"Contao sider",
file:"Contao filer",
link_title:"Tilføj/redigér link",
link_url:"Link URL",
link_target:"Åben link...",
link_target_same:"...i samme vindue",
link_target_blank:"...i nyt vindue",
link_titlefield:"Titel",
link_is_email:"Det lader til at du har indtastet en email adresse. Vil du automatisk tilføje \'mailto:\' prefix?",
link_is_external:"Det lader til at du har indtastet en email adresse. Vil du automatisk tilføje \'http://\' prefix?",
link_list:"Link liste",
image_title:"Tilføj/redigér lightbox billede",
image_list:"Billede liste",
image_src:"Billede URL",
image_dimensions:"Bredde/højde",
image_alt:"Beskrivelse",
image_class:"CSS klasse",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Type",
image_rel_single:"Enkelt billede",
image_rel_multi:"Billedgalleri"
});