tinyMCE.addI18n('en.typolinks_dlg',{
page:"Contao pages",
file:"Contao files",
link_title:"Insert/edit link",
link_url:"Link URL",
link_target:"Target",
link_target_same:"Open link in the same window",
link_target_blank:"Open link in a new window",
link_titlefield:"Title",
link_is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
link_is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
link_list:"Link list",
image_title:"Insert/edit a thumbnail image",
image_list:"Image list",
image_src:"Image URL",
image_dimensions:"Width/height",
image_alt:"Description",
image_class:"CSS class",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Lightbox",
image_rel_single:"Single element",
image_rel_multi:"Gallery"
});