tinyMCE.addI18n('pl.typolinks_dlg',{
page:'Strony Contao',
file:'Pliki Contao',
link_title:"Wstaw/edytuj link",
link_url:"Link URL",
link_target:"Cel",
link_target_same:"Otwórz link w tym samym oknie",
link_target_blank:"Otwórz link w nowym oknie",
link_titlefield:"Title",
link_is_email:"Wprowadzony URL wygląda na adres email, czy chcesz dostawić wymagany prefix mailto: ?",
link_is_external:"Wprowadzony URL wygląda na zewnętrzny link, czy chcesz dostawić wymagany prefix http:// ?",
link_list:"Lista linków",
image_title:"Insert/edit a thumbnail image",
image_list:"Image list",
image_src:"Image URL",
image_dimensions:"Width/height",
image_alt:"Description",
image_class:"CSS class",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Lightbox",
image_rel_single:"Single element",
image_rel_multi:"Gallery"
});