tinyMCE.addI18n('sl.typolinks_dlg',{
page:"Contao strani",
file:"Contao datoteke",
link_title:"Vstavi/uredi povezavo",
link_url:"Povezava URL",
link_target:"Ciljno okno",
link_target_same:"Odpri povezavo v istem oknu",
link_target_blank:"Odpri povezavo v novem oknu",
link_titlefield:"Naslov",
link_is_email:"URL, ki ste ga vnesli, se zdi, da je e-naslov, želite dodati zahtevano mailto: predpono?",
link_is_external:"URL, ki ste ga vnesli, se zdi, da je zunanja povezava, želite dodati zahtevano predpono http://?",
link_list:"Seznam povezav",
image_title:"Vstavi/uredi lightbox sliko",
image_list:"Seznam slik",
image_src:"URL slike",
image_dimensions:"Širina/višina",
image_alt:"Opis",
image_class:"CSS klas",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Lightbox",
image_rel_single:"Samostojni element",
image_rel_multi:"Galerija"
});