tinyMCE.addI18n('uk.typolinks_dlg',{
page:"Сторінки Contao",
file:"Файли Contao",
link_title:"Вставити/редагувати посилання",
link_url:"URL посилання",
link_target:"Відкриття посилання",
link_target_same:"Відкрити посилання в цьому ж вікні",
link_target_blank:"Відкрити посилання в новому вікні",
link_titlefield:"Заголовок",
link_is_email:"Схоже що введене значення URL є адресою електронної пошти, додати префікс mailto:?",
link_is_external:"Схоже що введене значення URL є зовнішнім посиланням, додати префікс http://?",
link_list:"Список посилань",
image_title:"Вставити/редагувати зображення в лайтбоксі",
image_list:"Список зображень",
image_src:"URL зображення",
image_dimensions:"Ширина/висота",
image_alt:"Опис",
image_class:"Клас CSS",
image_resize_mode:"Зміна розміру",
image_crop:"Точний розмір",
image_proportional:"Пропорційно",
image_box:"Встановити поле",
image_rel:"Тип",
image_rel_single:"Одне зображення",
image_rel_multi:"Галерея зображень"
});