tinyMCE.addI18n('fr.typolinks_dlg',{
page:"Pages Contao",
file:"Fichiers Contao",
link_title:"Insérer/éditer le lien",
link_url:"URL du lien",
link_target:"Cible",
link_target_same:"Ouvrir le lien dans la même fenêtre",
link_target_blank:"Ouvrir le lien dans une nouvelle fenêtre",
link_titlefield:"Titre",
link_is_email:"L'URL indiquée semble être une adresse e-mail, voulez-vous ajouter le préfixe mailto: ?",
link_is_external:"L'URL indiquée semble être un lien externe, voulez-vous ajouter le préfixe http:// ?",
link_list:"Liste des liens",
image_title:"Insert/edit a thumbnail image",
image_list:"Image list",
image_src:"Image URL",
image_dimensions:"Width/height",
image_alt:"Description",
image_class:"CSS class",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Lightbox",
image_rel_single:"Single element",
image_rel_multi:"Gallery"
});