tinyMCE.addI18n('pl.xhtmlxtras_dlg',{
attribute_label_title:"Tytu\u00C4\u0161\u00C2\u0082",
attribute_label_id:"ID",
attribute_label_class:"Klasa",
attribute_label_style:"Styl",
attribute_label_cite:"Cytat",
attribute_label_datetime:"Data/Czas",
attribute_label_langdir:"Kierunek tekstu",
attribute_option_ltr:"Kierunek z lewej do prawej",
attribute_option_rtl:"Kierunek z prawej do lewej",
attribute_label_langcode:"J\u0102\u0084\u00C2\u0099zyk",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"AccessKey",
attribute_events_tab:"Wydarzenia",
attribute_attrib_tab:"Atrybuty",
general_tab:"G\u00C4\u0161\u00C2\u0082\u00C4\u0082\u0139\u0082wny",
attrib_tab:"Atrybuty",
events_tab:"Wydarzenia",
fieldset_general_tab:"G\u00C4\u0161\u00C2\u0082\u00C4\u0082\u0139\u0082wne ustawienia",
fieldset_attrib_tab:"Atrybuty",
fieldset_events_tab:"Zda\u00C4\u0161\u0139\u015Fenia",
title_ins_element:"Insertion Element",
title_del_element:"Deletion Element",
title_acronym_element:"Akronim Element",
title_abbr_element:"Abbreviation Element",
title_cite_element:"Cytat",
remove:"Remove",
insert_date:"Wklej aktualn\u0102\u0084\u00C2\u0085 dat\u0102\u0084\u00C2\u0099/czas",
option_ltr:"Kierunek z lewej do prawej",
option_rtl:"Kierunek z prawej do lewej",
attribs_title:"Wklej/edytuj Attributes"
});