#!/usr/bin/env php
<?php

$root = dirname(dirname(__DIR__));

// Helper function to scan a directory
function scan($dir) {
	$return = array();
	foreach (scandir($dir) as $file) {
		if (strncmp($file, '.', 1) !== 0) {
			$return[] = $file;
		}
	}
	return $return;
}

// Create the source directory
if (!is_dir("$root/system/transifex/source")) {
	mkdir("$root/system/transifex/source");
} else {

	// Empty the source directory
	foreach (scan("$root/system/transifex/source") as $module) {
		if (!is_dir("$root/system/transifex/source/$module")) {
			continue;
		}
		foreach (scan("$root/system/transifex/source/$module") as $file) {
			@unlink("$root/system/transifex/source/$module/$file");
		}
		@rmdir("$root/system/transifex/source/$module");
	}
}

// Create the .tx/config file
$fh = fopen("$root/.tx/config", 'wb');
fputs($fh, "[main]\nhost = https://www.transifex.com\ntype = ANDROID\n");

// Scan the modules folder
foreach (scan("$root/system/modules") as $module) {
	if (!is_dir("$root/system/modules/$module/languages/en")) {
		continue;
	}

	// Create the subdirectory
	if (!is_dir("$root/system/transifex/source/$module")) {
		mkdir("$root/system/transifex/source/$module");
	}

	// Scan the language files
	foreach (scan("$root/system/modules/$module/languages/en") as $file) {
		if (substr($file, -4) != '.php') {
			continue;
		}

		// Create the XML document
		$xml = new DOMDocument();
		$xml->formatOutput = true;
		$resources = $xml->createElement('resources');
		$xml->appendChild($resources);

		// Reset the TL_LANG array before the include
		$GLOBALS['TL_LANG'] = array();
		include "$root/system/modules/$module/languages/en/$file";
		$file = basename($file, '.php');

		// Add the labels
		foreach ($GLOBALS['TL_LANG'] as $category=>$labels) {
			foreach ($labels as $key=>$label) {
				if (is_array($label)) {
					foreach ($label as $i=>$text) {
						if (is_array($text)) {
							foreach ($text as $j=>$subtext) {
								$string = $xml->createElement('string');
								$string->setAttribute('name', "$module:$file:$category:$key:$i:$j");
								$string->appendChild($xml->createTextNode($subtext));
								$resources->appendChild($string);
							}
						} else {
							$string = $xml->createElement('string');
							$string->setAttribute('name', "$module:$file:$category:$key:$i");
							$string->appendChild($xml->createTextNode($text));
							$resources->appendChild($string);
						}
					}
				} else {
					$string = $xml->createElement('string');
					$string->setAttribute('name', "$module:$file:$category:$key");
					$string->appendChild($xml->createTextNode($label));
					$resources->appendChild($string);
				}
			}
		}

		// Save the XML document
		$xml->save("$root/system/transifex/source/$module/$file.xml");

		// Add an entry to the .tx/config file
		fputs($fh, "\n[contao.$module-$file]\nsource_file = system/transifex/source/$module/$file.xml\nsource_lang = en\n");
	}
}

// Close the .tx/config file
fclose($fh);

echo "Opeation completed\n";
