tinyMCE.addI18n('it.typolinks_dlg',{
page:"Pagine Contao",
file:"File Contao",
link_title:"Inserisci/modifica link",
link_url:"Link URL",
link_target:"Destinazione",
link_target_same:"Apri il link nella stessa finestra",
link_target_blank:"Apri il link in una nuova finestra",
link_titlefield:"Titolo",
link_is_email:"L'URL inserito sembra essere un indirizzo e-mail, si vuole aggiungere la parola chiave mailto: come prefisso?",
link_is_external:"L'URL inserito sembra essere un link esterno, si vuole aggiungere la parola chiave http:// come prefisso?",
link_list:"Lista link",
image_title:"Inserisci/modifica image a dimensioni intera",
image_list:"Lista immagini",
image_src:"URL immagine",
image_dimensions:"Larghezza/altezza",
image_alt:"Descrizione",
image_class:"Classe CSS",
image_resize_mode:"Resize mode",
image_crop:"Exact dimensions",
image_proportional:"Proportional",
image_box:"Fit the box",
image_rel:"Lightbox",
image_rel_single:"Immagine singola",
image_rel_multi:"Gallera immagini"
});